/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v1.4 December 2012
 Copyright(c) 2012 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var Tee=Tee||{};
(function(){function p(d,b){this.x=d;this.y=b}function N(d,b,a,c){function e(){var c,e;if(a.x==b.x&&a.y==b.y)c=d.x-b.x,e=d.y-b.y;else{c=a.x-b.x;e=a.y-b.y;var g=((d.x-b.x)*c+(d.y-b.y)*e)/(c*c+e*e);0>g?(c=d.x-b.x,e=d.y-b.y):1<g?(c=d.x-a.x,e=d.y-a.y):(c=d.x-(b.x+g*c),e=d.y-(b.y+g*e))}return Math.sqrt(c*c+e*e)}return d.x==b.x&&d.y==b.y||d.x==a.x&&d.y==a.y?!0:Math.abs(e())<=c+1}function r(d,b,a,c){this.set(d,b,a,c)}function J(){this.left=this.right=this.top=this.bottom=2;this.apply=function(d){var b=d.width,
a=d.height;d.x+=0.01*b*this.left;d.width-=0.01*b*Math.min(100,this.left+this.right);d.y+=0.01*a*this.top;d.height-=0.01*a*Math.min(100,this.top+this.bottom)}}function O(d,b,a){this.format=a;this.bounds=b;var c=this,b=a.shadow;this.old=new B;this.old.set(b);b.visible=!0;b.color="rgba(0,255,0,0.1)";b.blur=10;b.width=0;b.height=0;this.enabled=!0;a=new Tee.Animation(a.chart,function(a){c.enabled&&(1>a?c.format.shadow.color="rgba(0,255,0,"+a.toString()+")":c.autoHide&&c.restore())});a.duration=d;a.animate();
this.restore=function(){this.format.shadow.set(this.old);this.enabled=!1}}function A(d){this.chart=d;this.visible=!1;this.colors=["white","silver"];this.direction="topbottom";this.stops=null;this.offset={x:0,y:0};this.create=function(b,a){return this.rect(b.x,b.y,b.width,b.height,a)};this.rect=function(b,a,c,e,d){var f;f=this.chart.ctx;var g=f.createLinearGradient;"topbottom"==this.direction?f=g.call(f,b,a,b,a+e):"bottomtop"==this.direction?f=g.call(f,b,a+e,b,a):"leftright"==this.direction?f=g.call(f,
b,a,b+c,a):"rightleft"==this.direction?f=g.call(f,b+c,a,b,a):"radial"==this.direction?(b=b+0.5*c+this.offset.x,a=a+0.5*e+this.offset.y,c=Math.max(c,e),f=f.createRadialGradient(b,a,0,b,a,c)):f="diagonalup"==this.direction?g.call(f,b,a+e,b+c,a):g.call(f,b,a,b+c,a+e);d&&this.setEndColor(d);c=this.colors;e=c.length;b=(a=this.stops)?a.length:0;if(1<e)for(d=0;d<e;d++)f.addColorStop(b<=d?d/(e-1):a[d],c[d]);else f.addColorStop(0,0<e?c[0]:"white");return f}}function B(d){this.chart=d;this.visible=!1;this.blur=
4;this.color="rgba(80,80,80,0.75)";this.height=this.width=4;this.prepare=function(b){this.visible?(b.shadowBlur=this.blur,b.shadowColor=this.color,b.shadowOffsetX=this.width,b.shadowOffsetY=this.chart.isAndroid?-this.height:this.height):b.shadowColor="transparent"}}function K(d){this.url="";this.chart=d;this.visible=!0;this.tryDraw=function(b,a,c,e){this.image||(this.image=new Image,this.image.onload=function(){d.draw()});""==this.image.src?(d=this.chart,this.image.src=this.url):d.ctx.drawImage(this.image,
b,a,c,e)}}function C(d){this.chart=d;this.fill="black";this.size=1;this.join="round";this.cap="square";this._g=this.dash=null;v?v(this,"gradient",{get:function(){this._g||(this._g=new A(this.chart));return this._g}}):this._g=this.gradient=new A(d);this.prepare=function(b,a){var a=a||this.chart.ctx,c=this._g;a.strokeStyle=c&&c.visible?c.create(this.chart.bounds):b?b:this.fill;a.lineWidth=this.size;a.lineJoin=this.join;a.lineCap=this.cap;a.shadowColor="transparent";a.setLineDash?a.setLineDash(this.dash):
a.mozCurrentTransform?a.mozDash=this.dash:this.chart.isChrome&&(a.webkitLineDash=this.dash)};this.setChart=function(b){this.chart=b;this._g&&(this._g.chart=b)}}function D(d){this.chart=d;this.style="11px Tahoma";this._g=null;v?v(this,"gradient",{get:function(){this._g||(this._g=new A(this.chart));return this._g}}):this._g=this.gradient=new A(d);this.fill="black";this._sh=null;v?v(this,"shadow",{get:function(){this._sh||(this._sh=new B(this.chart));return this._sh}}):this._sh=this.shadow=new B(d);
this._s=null;v?v(this,"stroke",{get:function(){this._s||(this._s=new C(this.chart),this._s.fill="");return this._s}}):(this._s=this.stroke=new C(d),this._s.fill="");this.textAlign="center";this.baseLine="alphabetic"}function P(d){this.chart=d;this.items=[];this.draw=function(){for(var b=0,a;a=this.items[b++];)a.active&&a.draw()};this.mousemove=function(b){for(var a=0,c;c=this.items[a++];)c.active&&c.mousemove(b)};this.mousedown=function(b){for(var a=0,c,e=!1;c=this.items[a++];)c.active&&c.mousedown(b)&&
(e=!0);return e};this.mouseout=function(){for(var b=0,a;a=this.items[b++];)a.active&&a.mouseout()};this.clicked=function(b){for(var a=0,c,e=!1;c=this.items[a++];)c.active&&c.clicked(b)&&(e=!0,c.onclick&&(e=c.onclick(c,b.x,b.y)));return e};this.add=function(b){this.items.push(b);return b}}function Q(d){function b(a){var b=a.chart.chartRect,d=a.direction,g="both"==d;c.set(b.x,b.y,b.width,b.height);if(a.old){if(g||"horizontal"==d)0>a.old.x?(c.x=a.chart.oldPos.x+a.old.x,c.width=-a.old.x):(c.x=a.chart.oldPos.x,
c.width=a.old.x);if(g||"vertical"==d)0>a.old.y?(c.y=a.chart.oldPos.y+a.old.y,c.height=-a.old.y):(c.y=a.chart.oldPos.y,c.height=a.old.y)}return c}this.chart=d;this.active=!1;this.enabled=!0;this.done=!1;this.direction="both";this.mouseButton=0;var a=this.format=new Tee.Format(d);a.fill="rgba(255,255,255,0.5)";a.stroke.fill="darkgray";a.stroke.size=2;var c=new r;this.draw=function(){a.rectangle(b(this))};this.apply=function(){if(0>this.old.x||0>this.old.y){if(this.reset(),this.onreset)this.onreset()}else if(b(this),
3<c.width&&3<c.height)return this.chart.axes.each(function(){this.horizontal?this.calcMinMax(c.x,c.x+c.width):this.calcMinMax(c.y+c.height,c.y)}),!0;return!1};this.reset=function(){this.chart.axes.each(function(){this.automatic=!0})}}function R(d){this.chart=d;this.active=!1;this.enabled=!0;this.done=!1;this.mouseButton=2;this.direction="both";this.position=new p(0,0)}function I(d,b){Tee.Annotation.call(this,d);this.transparent=!0;this._expand=!1;v?v(this,"expand",{get:function(){return this._expand},
set:function(a){this._expand=a;this._expand||(a=this.format,a.round.x=8,a.round.y=8,a.round.corners=null,a.stroke.fill="black")}}):this._expand=this.expand=!1;var a=this.format.font,c=a.shadow,e=this.position;c.visible=!0;c.width=2;c.height=2;c.blur=8;a.style="18px Tahoma";a.fill=b;this.padding=4;this.calcRect=function(a){this.resize();var c=this.bounds,b=c.height+(this.transparent?1:2)*this.padding,j=d.chartRect;a?(e.y=j.y,j.setTop(j.y+b)):(e.y=j.y+j.height-c.height-this.padding,j.height-=b);0>j.height&&
(j.height=0);e.x=0.5*(d.canvas.width-c.width)};this.tryDraw=function(a){if(this.visible&&this.text&&""!==this.text){this.calcRect(a);var c=this.bounds;if(this._expand){var b=d.panel.format;e.x=""!=b.stroke.fill?b.stroke.size:0;e.y=a?e.x:d.canvas.height-(b.shadow.visible?b.shadow.height:0)-e.x-c.height;c.width=d.canvas.width-(b.shadow.visible?b.shadow.width:0)-2*e.x;var j=this.format;j.round.x=b.round.x;j.round.y=b.round.y;j.round.corners=[a,a,!a,!a];j.stroke.fill="";this.transparent=!1}c.x=e.x;c.y=
e.y;this.doDraw()}}}function S(d){var b=this.format=new Tee.Format(d);b.round.x=12;b.round.y=12;b.stroke.size=3;b.gradient.visible=!0;b.gradient.direction="bottomtop";b.shadow.visible=!0;b.stroke.fill="#606060";this.transparent=!1;this.margins=new J;this.clear=function(){var a=d.bounds;d.ctx.clearRect(a.x,a.y,a.width,a.height)};this.draw=function(){if(this.transparent)this.clear();else{var a=d.chartRect,c=b.shadow;c.visible&&(a.width-=0.5*Math.abs(c.width)+2,a.height-=0.5*Math.abs(c.height)+2,0>c.width&&
(a.x-=c.width),0>c.height&&(a.y-=c.height));var e=0;""!=b.stroke.fill&&(e=b.stroke.size,1<e&&(e*=0.5,a.x+=e,a.y+=e,a.width-=2*e,a.height-=2*e));(c.visible||0<b.round.x||0<b.round.y)&&this.clear();b.rectangle(a);0<e&&(a.x+=e,a.y+=e,a.width-=2*e,a.height-=2*e)}}}function G(d){this.format=new Tee.Format(d);this.format.fill="#E6E6E6";this.format.stroke.fill="black";this.visible=!0;this.bounds=new r;this.draw=function(){this.format.rectangle(this.bounds)}}function w(d,b,a){function c(a){this.chart=a;this.stroke=
new C(a);this.stroke.cap="butt";this.visible=!0;this.length=4}function e(a){Tee.Annotation.call(this,a);this.padding=4;this.transparent=!0;this.format.font.textAlign="center"}function i(a,c){var b=0,e,d=c.split(" "),f;for(f=0;f<d.length;f++)e=a.textWidth(d[f]),e>b&&(b=e);return b}function f(a){return isFinite(a)?10<=a?10*f(0.1*a):1>a?0.1*f(10*a):2>a?2:5>a?5:10:1}this.chart=d;this.visible=!0;this.inverted=!1;this.horizontal=b;this.otherSide=a;this.bounds=new r;this.position=0;this.format=new Tee.Format(d);
this.format.stroke.size=2;this.custom=!1;this.labels=new function(a,c){this.chart=a;this.format=new Tee.Format(a);this.decimals=2;this.padding=4;this.separation=10;this.visible=!0;this.rotation=0;this.alternate=!1;this.maxWidth=0;this.wordWrap="no";this.labelStyle="auto";this.dateFormat="shortDate";this.checkStyle=function(){var a=this.labelStyle,b=c.firstSeries;this._text=null;if("auto"==a)0<b.data.labels.length&&b.notmandatory==c&&(this._text=b);else if("mark"==a||"text"==a)this._text=b};this.getLabel=
function(b){var e=b|0,d;if(this._text&&e==b){if(d=this._text.data,d.x&&(e=d.x.indexOf(e)),d=d.labels[e],!d){var f=a.series.items,i,g;for(i=0;(g=f[i++])&&(!(g!=this._text&&g.visible&&g.associatedToAxis(c))||!(d=g.data.labels[e])););"undefined"===typeof d&&(d="")}}else d=c.dateTime&&Date.prototype.format?(new Date(b)).format(this.dateFormat):this.valueFormat?b.toLocaleString():b.toFixed(e==b?0:this.decimals);this.ongetlabel&&(d=this.ongetlabel(b,d),this.format.font.prepare());return""+d};this.width=
function(a){return this.format.textWidth(this.getLabel(a))}}(d,this);var g=this.labels.format.font;this.scroll=function(a){this.automatic=!1;this.inverted&&(a=-a);this.minimum+=a;this.maximum+=a};b?(g.textAlign="center",g.baseLine=a?"bottom":"top"):(g.textAlign=a?"left":"right",g.baseLine="middle");this.grid=new function(a){this.chart=a;a=this.format=new Tee.Format(a);a.stroke.fill="silver";a.stroke.cap="butt";a.fill="";this.visible=!0;this.lineDash=!1}(d);this.ticks=new c(d);this.innerTicks=new c(d);
this.innerTicks.visible=!1;g=this.minorTicks=new c(d);g.visible=!1;g.length=2;g.count=3;e.prototype=new Tee.Annotation;this.title=new e(d);this.automatic=!0;this.increment=this.maximum=this.minimum=0;this.log=!1;this.start=this.endPos=this.startPos=0;this.end=100;this.increm=this.scale=this.axisSize=0;this.minmaxLabelWidth=function(){var a=this.labels,c=a._text,b=0,e,d;if(null!=c){d="auto"==a.wordWrap||"yes"==a.wordWrap;for(var f=0,g=c.data.labels.length;f<g;f++)e=c.data.labels[f],this.ongetlabel&&
(e=this.ongetlabel(f,e)),e&&(b=Math.max(b,d?i(a.format,e):a.format.textWidth(e)))}else b=this.roundMin(),c=this.maximum,b=Math.max(a.width(b),a.width(0.5*(b+c))),b=Math.max(b,a.width(1E-7)),b=Math.max(b,a.width(c));return b};this.checkMinMax=function(){var a=this.chart.series,c=this.horizontal;this.automatic&&(this.minimum=c?a.minXValue(this):a.minYValue(this),this.maximum=c?a.maxXValue(this):a.maxYValue(this))};this.calcAxisScale=function(){var a=this.maximum-this.minimum;0==a?a=1:this.log&&(a=Math.log(a));
this.scale=this.axisSize/a};this.calcScale=function(){var a=this.labels,c;a.format.font.prepare();c=this.horizontal?this.minmaxLabelWidth():a.format.textHeight("Wj");a.alternate&&(c*=0.5);c*=1+0.02*a.separation;if(0==this.increment)if(this.maximum==this.minimum)a=1;else{a=this.axisSize/c;b:{c=a;var b,e,d;for(b=0;e=this.chart.series.items[b++];)if(e.visible&&((d=e.yMandatory)&&this.horizontal||!d&&!this.horizontal)&&e.associatedToAxis(this)&&e.count()<=c){c=!0;break b}c=!1}a=Math.abs(this.maximum-
this.minimum)/(a+1);a=c?Math.max(1,a):f(a)}else a=this.increment;this.increm=a;0>=this.increm&&(this.increm=0.1)};this.hasAnySeries=function(){var a=this.chart.series.items,c,b;for(c=0;b=a[c++];)if(b.visible&&b.associatedToAxis(this))return a=this.horizontal,b.yMandatory&&(a=!a),this.dateTime=(a=a?b.data.values:b.data.x)&&0<a.length&&a[0]instanceof Date,b;return null};this.drawAxis=function(){var a=this.chart.ctx,c=this.axisPos,e=this.startPos,d=this.endPos;a.beginPath();b?(a.moveTo(e,c),a.lineTo(d,
c)):(a.moveTo(c,e),a.lineTo(c,d));this.format.stroke.prepare();a.stroke()};this.drawGrids=function(){var c=this.chart.ctx,e,d=this.chart.chartRect,f=this.grid.format,i,g,n,s,l=this.roundMin();this.grid.centered&&(e=0.5*this.increm,l=l-e>=this.minimum?l-e:l+e);c.beginPath();b?(g=this.bounds.y,s=a?d.getBottom()-1:d.y+1):(i=this.bounds.x,n=a?d.x+1:d.getRight()-1);if(""!=f.fill){var d=l,z=f.stroke.fill;f.stroke.fill="";for(var x,p=-1;d<=this.maximum;)e=this.calc(d),0==p%2&&(b?f.rectangle(x,s,e-x,g-s):
f.rectangle(i,x,n-i,e-x)),x=e,d+=this.increm,p++;f.stroke.fill=z;c.fillStyle=""}for(d=l;d<=this.maximum;){p=this.calc(d);b?i=n=p:g=s=p;if(f.stroke.dash&&!c.setLineDash&&!c.mozCurrentTransform){l=c;x=i;var p=g,r=n,z=s;e=void 0;e=[10,5];l.save();var r=r-x,t=z-p,z=Math.sqrt(r*r+t*t),r=Math.atan2(t,r);l.translate(x,p);l.moveTo(0,0);l.rotate(r);p=e.length;r=0;t=!0;for(x=0;z>x;)x+=e[r++%p],x>z&&(x=z),t?l.lineTo(x,0):l.moveTo(x,0),t=!t;l.restore()}else c.moveTo(i,g),c.lineTo(n,s);d+=this.increm}f.stroke.prepare();
f.shadow.prepare(c);c.stroke()};this.roundMin=function(){var a=this.minimum/this.increm|0;return this.increm*(0>=this.minimum?a:1+a)};this.drawTicks=function(c,e,d){var f=this.roundMin(),i=1+c.length,g=1;if(b&&a||!b&&!a)i=-i,g=-1;var i=i*e+this.axisPos,g=g*e+this.axisPos,n,s=1,l=0;0==d?n=this.increm:(s+=d,n=this.increm/s);var z=this.chart.ctx;for(z.beginPath();f<=this.maximum;){if(0==d||0!=l++%s)e=this.calc(f),b?(z.moveTo(e,g),z.lineTo(e,i)):(z.moveTo(g,e),z.lineTo(i,e));f+=n}c.stroke.prepare();z.stroke()};
this.drawTitle=function(){var a=this.labels,c,e;""!=this.title.text&&(b?(e=this.axisPos+this.title.padding,this.ticks.visible&&(e+=this.ticks.length),a.visible&&(a.format.font.prepare(),c=a.format.textHeight("Wj"),a.alternate&&(c*=2),e+=c),c=this.startPos+0.5*this.axisSize-0.5*this.title.bounds.width,this.title.position.x=c,this.title.position.y=e,this.title.forceDraw()):(c=this.axisPos-this.title.bounds.height-this.title.padding,this.ticks.visible&&(c-=this.ticks.length),a.visible&&(e=a.maxWidth,
a.alternate&&(e*=2),c-=e),e=this.startPos+0.5*(this.axisSize+this.title.bounds.width)+this.title.bounds.height,a=this.chart.ctx,a.save(),a.translate(c,e),a.rotate(-Math.PI/2),a.textAlign="center",this.title.position.x=0,this.title.position.y=0,this.title.forceDraw(),a.restore()))};this.drawLabel=function(a,c){var b=this.labels,e=b.getLabel(a);c.width=b.format.textWidth(e);c.width>b.maxWidth&&(b.maxWidth=c.width);this.horizontal?c.x-=0.5*c.width:c.y+=0.5*c.height;if(0!=b.rotation){var d=this.chart.ctx;
d.save();d.translate(c.x,c.y);d.rotate(-Math.PI*b.rotation/180);d.textAlign="right";c.x=-8;c.y=3}"right"==b.format.font.textAlign&&(c.x-=c.width);b.format.drawText(c,e);0!=b.rotation&&this.chart.ctx.restore()};this.drawLabels=function(){var a=this.roundMin(),c=new r,b=this.axisPos,e=this.labels;e.maxWidth=0;e.format.font.prepare();var d=this.ticks.visible?this.ticks.length:0,d=d+e.padding;this.horizontal?this.otherSide?b-=d:b+=d:this.otherSide?b+=d:b-=d;d=b;c.height=e.format.textHeight("Wj");for(var f=
(e=e.alternate)?this.horizontal?-c.height:this.minmaxLabelWidth():0,i;a<=this.maximum;)i=this.calc(a),this.horizontal?(c.x=i,c.y=b):(c.x=b,c.y=i-0.5*c.height),e&&(b=b==d?this.otherSide?d+f:d-f:d),this.drawLabel(a,c),a+=this.increm};this.calc=function(a){a!==a?a=0:this.log?(a-=this.minimum,a=0>=a?0:Math.log(a)*this.scale):a=(a-this.minimum)*this.scale;return this.horizontal?this.inverted?this.endPos-a:this.startPos+a:this.inverted?this.startPos+a:this.endPos-a};this.fromPos=function(a){var c=this.horizontal;
this.inverted&&(c=!c);return this.minimum+(c?a-this.startPos:this.endPos-a)/this.scale};this.fromSize=function(a){return a/this.scale};this.calcSize=function(a){return Math.abs(this.calc(a)-this.calc(0))};this.calcMinMax=function(a,c){this.automatic=!1;var b=this.fromPos(a),e=this.fromPos(c),d;b>e&&(d=b,b=e,e=d);this.minimum=b;this.maximum=e};this.setMinMax=function(a,c){this.automatic=!1;this.minimum=a;this.maximum=c}}function T(d){this.chart=d;this.transparent=!1;var b=this.format=new Tee.Format(d);
b.fill="white";b.round.x=8;b.round.y=8;b.font.baseLine="top";b.shadow.visible=!0;this.title=new Tee.Annotation(d);this.title.transparent=!0;this.bounds=new r;this.position="right";this.visible=!0;this.inverted=!1;this.margin=this.padding=5;this.align=0;this.fontColor=!1;var a=this.dividing=new C(d);a.fill="";a.cap="butt";this.over=-1;this.symbol=new function(a){this.chart=a;var c=this.format=new Tee.Format(a),b=c.shadow;b.visible=!0;b.color="silver";b.width=2;b.height=2;this.padding=this.height=this.width=
8;this.style="rectangle";this.visible=!0;this.draw=function(b,e,d,f){var i=a.ctx,h;a:{if(b.hover.enabled&&((h=a.legend.showValues())&&b.over==e||!h&&0<=b.over)){h=b.hover;break a}h=null}var g=c.fill,j=c.stroke;c.fill=b.isColorEach&&-1!=e?b.getFill(e):b.format.fill;"rectangle"===this.style?(h&&(c.stroke=h.stroke),c.rectangle(d,f-0.5*this.height-1,this.width,this.height)):(i.beginPath(),i.moveTo(d,f),i.lineTo(d+this.width,f),h?h.stroke.prepare():c.stroke.prepare(c.fill),i.stroke());c.fill=g;c.stroke=
j}}(d);this.itemHeight=10;this.innerOff=0;this.textStyle=this.legendStyle="auto";this.totalWidth=function(){var a=j+8,c=this.symbol;c.visible&&(a+=c.width+c.padding);return a};var c=0;this._space=function(){return this.bounds.y+c+0.01*this.margin*d.bounds.height};this.availRows=function(){var a=this._space()+0.5*this.itemHeight;a||(a=0);return(d.bounds.getBottom()-a)/this.itemHeight|0};this.itemsCount=function(){var a=d.series,c=a.visibleCount(),b=d.bounds;if(0==c)return 0;"values"==this.legendStyle&&
0<c?c=a.firstVisible().count():"auto"==this.legendStyle&&1<c||"series"==this.legendStyle||1==c&&(c=a.firstVisible().count());if(this.isVertical())(0.5+c)*this.itemHeight>b.height-this._space()&&(c=this.availRows());else{this.rows=1;var a=this.totalWidth(),e=this.calcPadding(b),e=b.width-2*e;c*a>e?(this.perRow=e/a|0,c>this.perRow&&(this.rows=1+(c/this.perRow|0),this.rows*this.itemHeight>b.height-this.bounds.y&&(this.rows=this.availRows(),c=this.rows*this.perRow))):this.perRow=c}return c};this.showValues=
function(){var a=this.legendStyle;return"values"==a||"auto"==a&&1==d.series.visibleCount()};this.itemText=function(a,c){var b=a.dataText(c,this.textStyle,!1,!0);return this.ongettext?this.ongettext(this,a,c,b):b};this.calcItemPos=function(a,b){var e=this.itemHeight,d=this.bounds;b.x=d.x;b.y=d.y+this.innerOff;this.isVertical()?(b.x+=d.width-6-this.innerOff,b.y+=0.4*e+a*e+c):(b.x+=this.innerOff+(1+a%this.perRow)*this.totalWidth(),b.y+=e*((a/this.perRow|0)+0.25))};this.calcItemRect=function(a,b){var e=
this.itemHeight,d=this.bounds;b.height=e;b.x=d.x;b.y=d.y;this.isVertical()?(b.width=d.width,b.y+=0.4*e+a*e+c):(b.width=this.totalWidth(),b.x+=this.innerOff+a%this.perRow*b.width,b.y+=e*((a/this.perRow|0)+0.25))};var e=new r;this.mousemove=function(a){var c=this.over;if(this.bounds.contains(a))for(var b=this.itemsCount(),d=0;d<b;d++){if(this.calcItemRect(d,e),e.contains(a)){c=d;break}}else c=-1;if(c!=this.over){if(this.onhover)this.onhover(this.over,c);this.over=c;var f=this.chart;window.requestAnimFrame(function(){f.draw()})}};
this.drawSymbol=function(a,c,b){var e=this.symbol;e.draw(a,c,b.x-j-e.width-e.padding,b.y+0.4*this.itemHeight)};var i={x:0,y:0},f=new r,g;this.drawItem=function(a,c,e,u){var n=this.isVertical();this.calcItemPos(e,i);f.x=i.x;f.y=i.y;n?f.y-=this.chart.isMozilla?0:2:this.chart.isMozilla?f.y++:f.y--;var s=b.font.fill;this.over==e?b.font.fill="red":this.fontColor&&(b.font.fill=this.showValues()?c.getFill(e):c.format.fill);var l=this.chart.ctx;if(u)b.font.textAlign="start",f.x-=h[0],l.textAlign=b.font.textAlign,
b.drawText(f,a);else if(a instanceof Array||(a=[a]),n){for(var u=a.length,n=f.width,p=b.textWidth(" ");u--;)b.font.textAlign=g[u]?"start":"end",f.x-=h[u],l.textAlign=b.font.textAlign,b.drawText(f,a[u]),f.width-=h[u]+p;f.width=n}else b.font.textAlign="start",f.x-=j,l.textAlign=b.font.textAlign,b.drawText(f,a.join(" "));b.font.fill=s;l=!c.isColorEach||this.showValues();this.symbol.visible&&l&&this.drawSymbol(c,e,i);0<e&&""!=this.dividing.fill&&(l=d.ctx,c=this.bounds,l.beginPath(),this.isVertical()?
(l.moveTo(c.x,f.y-2),l.lineTo(c.getRight(),f.y-2)):(e=f.x-j-4,a=this.symbol,a.visible&&(e-=a.width+a.padding),l.moveTo(e,c.y),l.lineTo(e,c.getBottom())),this.dividing.prepare(),l.stroke())};this.drawSeries=function(a,c){var b=d.series.items[a];return b.visible?(this.drawItem(""==b.title?"Series "+a.toString():b.title,b,c,!0),!0):!1};this.draw=function(){var a=this.itemsCount(),e,i;e=this.title;var h=d.ctx,n,s=this.format.transparency,l=this.isVertical();if(0<a){this.transparent||b.rectangle(this.bounds);
0<s&&(n=h.globalAlpha,h.globalAlpha=(1-s)*n);l&&0<c&&(e.bounds.x=this.bounds.x-4,e.bounds.y=this.bounds.y,e.doDraw());b.font.prepare();f.width=j;f.height=this.itemHeight;if(this.showValues()){l=d.series.firstVisible();i=0;e=a;switch(this.textStyle){case "auto":case "percentlabel":case "valuelabel":g=[!1,!0];break;case "labelpercent":case "labelvalue":g=[!0,!1];break;case "label":g=[!0];break;default:g=[!1]}if(this.inverted)for(;e--;)this.drawItem(this.itemText(l,e),l,i++);else for(i=0;i<e;i++)this.drawItem(this.itemText(l,
i),l,i)}else if(e=d.series.count(),l&&(e=Math.min(e,this.availRows())),a=0,g=[!0],this.inverted)for(;e--;)this.drawSeries(e,a)&&a++;else for(i=0;i<e;i++)this.drawSeries(i,a)&&a++;0<s&&(h.globalAlpha=n)}};var j,h;this.calcWidths=function(){var a,c,e,f,i=d.series;j=0;h=[0,0];if(this.showValues()){a=i.firstVisible();f=this.itemsCount();for(c=0;c<f;c++)i=this.itemText(a,c),i instanceof Array||(i=[i]),0<i.length&&(e=b.textWidth(i[0]),e>h[0]&&(h[0]=e),1<i.length&&(e=b.textWidth(i[1]),e>h[1]&&(h[1]=e)))}else{f=
i.count();for(c=0;c<f;c++)a=i.items[c],a.visible&&(e=b.textWidth(a.title),e>h[0]&&(h[0]=e))}j=h[0]+h[1]};this.calcPadding=function(a){return 0.01*this.padding*(this.isVertical()?a.width:a.height)};this.isVertical=function(){return"right"==this.position||"left"==this.position};this.calcrect=function(){var a=0,e=this.title,f=d.chartRect,i=this.align,h=this.bounds,g=this.isVertical();e.visible&&""!=e.text?(e.resize(),c=e.bounds.height,a=e.bounds.width):c=0;g?h.y=0==i?f.y:0.01*d.bounds.height*i:h.x=0==
i?f.x:0.01*d.bounds.width*i;b.font.prepare();this.itemHeight=b.textHeight("Wj");this.calcWidths();var i=this.calcPadding(f),l=this.itemsCount();g?(g=this.symbol.visible?this.symbol.width+this.symbol.padding:0,h.width=Math.max(a,12+j+g),h.height=(0.5+l)*this.itemHeight+c,h.width-6>a&&(e.bounds.width=h.width-6)):(h.width=i+this.perRow*this.totalWidth(),h.x+=0.5*(f.width-h.width),h.height=this.itemHeight*(this.rows+0.25));""!=b.stroke.fill&&(g=+b.stroke.size,1<g&&(h.width+=g,h.height+=g,this.innerOff=
0.5*g));0!=l&&("right"==this.position?(h.x=f.getRight()-h.width-0.01*this.margin*h.width,f.setRight(Math.max(f.x,h.x-i))):"left"==this.position?(h.x=f.x,f.setLeft(h.x+h.width+i)):"top"==this.position?(h.y=f.y+i,f.setTop(h.getBottom()+i)):(h.y=f.getBottom()-h.height-i,f.setBottom(h.y-i)))}}function L(d,b){Tee.Annotation.call(this,b);this.series=d;this.arrow=new Tee.Format(b);this.arrow.length=10;this.arrow.underline=!1;this.style="auto";this.drawEvery=1;this.visible=!1;this.setChart=function(a){this.chart=
a;this.format.setChart(a);this.arrow.setChart(a)};this.drawPolar=function(a,c,b,d){var f=this.series.markText(d),d=a.x+Math.cos(b)*c,g=a.y+Math.sin(b)*c,j=this.chart.ctx;this.text=f;this.resize();var f=this.bounds,h,m=this.position,c=c+this.arrow.length;h=a.x+Math.cos(b)*c;c=a.y+Math.sin(b)*c;0>h-f.width&&(h-=h-f.width-4);m.x=Math.abs(h-a.x)<f.width?h-0.5*f.width:h<a.x?h-f.width:h;m.y=Math.abs(c-a.y)<f.height?c-0.5*f.height:c<a.y?c-f.height:c;j.beginPath();j.moveTo(d,g);j.lineTo(h,c);if(this.arrow.underline&&
(c<=m.y||c>=m.y+f.height))j.moveTo(m.x,c),j.lineTo(m.x+f.width,c);this.arrow.stroke.prepare();j.stroke();this.draw()};this.canDraw=function(a,c,b,d){var f=this.series.markText(b),b=this.arrow;if(f&&""!=f&&(this.showZero||"0"!=f)){this.text=f;this.resize();var f=d?-1:1,g=this.bounds;this.series.yMandatory?(g.x=a-0.5*g.width,g.y=c-f*(b.length+(d?0:g.height))):(g.x=a+f*b.length,d&&(g.x-=g.width),g.y=c-0.5*g.height);this.position.x=g.x;this.position.y=g.y;return!0}return!1};this.drawMark=function(a,c,
b,d){if(this.canDraw(a,c,b,d)){this.draw();var b=this.bounds,f=this.series.yMandatory,g=this.arrow,j=d?b.y:b.getBottom(),h=this.chart.ctx;h.beginPath();f?(h.moveTo(a,j),h.lineTo(a,c),g.underline&&(h.moveTo(b.x,j),h.lineTo(b.x+b.width,j))):(c=b.y+0.5*b.height,h.moveTo(a,c),d&&(b.x+=b.width),h.lineTo(b.x,c),g.underline&&(h.moveTo(b.x,b.y+b.height),h.lineTo(b.x+(d?-b.width:b.width),b.y+b.height)));g.stroke.prepare();h.stroke()}}}function U(d){for(var b=0,a=d.length;a--;)b+=d[a];return b}function M(d){this.chart=
d;this.items=[];this.count=function(){return this.items.length};this.clicked=function(b){var a=!1;this.each(function(c){if(c.visible&&c.onclick){var e=c.clicked(b);-1!=e&&(a=c.onclick(c,e,b.x,b.y))}});return a};this.mousedown=function(b){for(var a=0,c,e=!1;c=this.items[a++];)c.visible&&c.mousedown(b)&&(e=!0);return e};this.mousemove=function(b){for(var a=0,c;c=this.items[a++];)c.visible&&c.mousemove(b)};this.mouseout=function(){this.each(function(b){b.visible&&b.mouseout()})};this.visibleCount=function(b,
a,c){for(var e=0,d=this.items,f=d.length,g;f--,g=d[f];)if(g.visible&&(!a||g instanceof a))c&&g==b&&(c.index=e),e++;c&&(c.total=e,c.index=e-1-c.index);return e};this.beforeDraw=function(){this.each(function(b){b.useAxes&&b.recalcAxes();b.calcColorEach()})};this.anyUsesAxes=function(){for(var b=this.items.length,a;b--;)if(a=this.items[b],a.visible&&a.useAxes)return!0;return!1};this.firstVisible=function(){for(var b=0,a;a=this.items[b++];)if(a.visible)return a;return null};this.vertMargins=function(){var b,
a=this.items,c=a.length,e,d;if(0<c){b={x:0,y:0};e={x:0,y:0};a[0].vertMargins(b);for(d=1;d<c;d++)e.x=e.y=0,a[d].vertMargins(e),e.x>b.x&&(b.x=e.x),e.y>b.y&&(b.y=e.y)}return b};this.horizMargins=function(){var b,a=this.items,c=a.length,e,d;if(0<c){b={x:0,y:0};e={x:0,y:0};a[0].horizMargins(b);for(d=1;d<c;d++)e.x=e.y=0,a[d].horizMargins(e),e.x>b.x&&(b.x=e.x),e.y>b.y&&(b.y=e.y)}return b};this.minXValue=function(b){for(var a=Infinity,c=this.items.length,e;c--;)if(e=this.items[c],e.visible&&(!b||e.associatedToAxis(b)))e=
e.minXValue(),e<a&&(a=e);return a};this.minYValue=function(b){for(var a=Infinity,c=this.items.length,e;c--;)if(e=this.items[c],e.visible&&(!b||e.associatedToAxis(b)))e=e.minYValue(),e<a&&(a=e);return a};this.maxXValue=function(b){for(var a=-Infinity,c=this.items.length,e;c--;)if(e=this.items[c],e.visible&&(!b||e.associatedToAxis(b)))e=e.maxXValue(),e>a&&(a=e);return a};this.maxYValue=function(b){for(var a=-Infinity,c=this.items.length,e;c--;)if(e=this.items[c],e.visible&&(!b||e.associatedToAxis(b)))e=
e.maxYValue(),e>a&&(a=e);return a};this.draw=function(){var b=this.items.length,a=this.chart,c=a.ctx,e=a.aspect,d,f;if(0<b){var g=this.firstVisible();g&&g.beforeDraw&&g.beforeDraw();(g=e.clip&&this.anyUsesAxes())&&e.clipRect(a.chartRect);try{for(d=0;d<b;d++)if(f=this.items[d],f.visible){var j=c.globalAlpha;c.globalAlpha=1-f.format.transparency;f.transform&&(c.save(),f.transform());f.draw();if(f.ondraw)f.ondraw(f);f.transform&&c.restore();c.globalAlpha=j}}finally{g&&c.restore()}for(d=0;d<b;d++)f=this.items[d],
f.visible&&f.marks.visible&&(f.transform&&(c.save(),f.transform()),f.drawMarks(),f.transform&&c.restore())}}}function V(d){this.chart=d;this.visible=!0;this.transparency=0;this.left=new w(d,!1,!1);this.top=new w(d,!0,!0);this.right=new w(d,!1,!0);this.bottom=new w(d,!0,!1);this.items=[this.left,this.top,this.right,this.bottom];this.each=function(b){for(var a=0,c;c=this.items[a++];)b.call(c)};this.add=function(b,a){var c=new w(d,b,a);c.custom=!0;this.items.push(c);return c}}"undefined"!==typeof exports&&
(exports.Tee=Tee);"undefined"!==typeof window&&(window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(d){window.setTimeout(d,1E3/60,(new Date).getTime())});var v;try{Object.defineProperty({},"x",{}),v=Object.defineProperty}catch(W){}"indexOf"in Array.prototype||(Array.prototype.indexOf=function(d,b){void 0===b&&(b=0);0>b&&(b+=this.length);0>b&&(b=0);for(var a=
this.length;b<a;b++)if(b in this&&this[b]===d)return b;return-1});r.prototype.set=function(d,b,a,c){this.x=d;this.y=b;this.width=a;this.height=c};r.prototype.setFrom=function(d){this.x=d.x;this.y=d.y;this.width=d.width;this.height=d.height};r.prototype.getRight=function(){return this.x+this.width};r.prototype.getBottom=function(){return this.y+this.height};r.prototype.setTop=function(d){this.height-=d-this.y;this.y=d};r.prototype.setBottom=function(d){this.height=d-this.y};r.prototype.setLeft=function(d){this.width-=
d-this.x;this.x=d};r.prototype.setRight=function(d){this.width=d-this.x};r.prototype.contains=function(d){return d.x>=this.x&&d.x<=this.x+this.width&&d.y>=this.y&&d.y<=this.y+this.height};Tee.Tool=function(d){this.chart=d;this.active=!0};Tee.Animation=function(d,b){Tee.Tool.call(this,d);this.active=!0;this.mode="linear";this.duration=500;this.items=[];this.running=!1;this.onstop=this.onstart=null;d&&(d instanceof Tee.Chart?this.chart=d:d instanceof Tee.Animation&&(this.chart=d.chart,d.items.push(this)));
var a=null;this.animate=function(c){if(!this.running){this.running=!0;c&&(this.chart=c);this.init=(new Date).getTime();a=this;a.start();for(var c=0,b;b=a.items[c++];)b.active&&(b.chart=a.chart,b.start());a.chart.draw();requestAnimFrame(this.step,this)}};this.start=function(){if(this.onstart)this.onstart()};this.stop=function(){if(this.onstop)this.onstop()};this.doStep=function(a){b&&b(a)};this.step=function(){var c,b;c=((new Date).getTime()-a.init)/a.duration;var d="linear"==a.mode?c:Math.pow(2,10*
(c-1));if(0<=d&&1>d){a.doStep(d);for(c=0;b=a.items[c++];)b.active&&(b.chart=a.chart,b.doStep(d));a.chart.draw();requestAnimFrame(a.step,a)}else{a.stop();for(c=0;b=a.items[c++];)b.active&&(b.chart=a.chart,b.stop());if(a.onstop)a.onstop(a);a.running=!1;a.chart.draw()}}};Tee.Animation.prototype=new Tee.Tool;Tee.Tool.prototype.mousedown=function(){};Tee.Tool.prototype.mousemove=function(){};Tee.Tool.prototype.mouseout=function(){};Tee.Tool.prototype.clicked=function(){return!1};Tee.Tool.prototype.draw=
function(){};A.prototype.setEndColor=function(d){if(d&&""!==d)for(var b=1,a=this.colors.length;b<a;b++)this.colors[b]=d};B.prototype.set=function(d){this.visible=d.visible;this.color=d.color;this.blur=d.blur;this.width=d.width;this.height=d.height};D.prototype.getSize=function(){var d=this.style.split(" "),b,a;for(b=0;b<d.length;b++)if(a=parseFloat(d[b]))return a;return 20};D.prototype.setSize=function(d){var b="",a=this.style.split(" "),c;for(c=0;c<a.length;c++)parseFloat(a[c])?b+=d.toString()+"px ":
b+=a[c]+" ";this.style=b};D.prototype.prepare=function(){var d=this.chart.ctx;d.textAlign=this.textAlign;d.textBaseline=this.baseLine;this._sh&&this._sh.prepare(d);d.font!=this.style&&(d.font=this.style)};D.prototype.setChart=function(d){this.chart=d;this._g&&(this._g.chart=d);this._sh&&(this._sh.chart=d);this._s&&this._s.setChart(d)};Tee.Format=function(d){this.chart=d;this.gradient=new A(d);this.fill="rgb(200,200,200)";this.stroke=new C(d);this.round={x:0,y:0};this.transparency=0;this.font=new D(d);
this._img=null;v?v(this,"image",{get:function(){this._img||(this._img=new K(this.chart));return this._img}}):this._img=this.image=new K(d);this.shadow=new B(d);this.roundRect=function(a,c,b,d,f){if(a.roundRect)a.roundRect(c,b,d,f,this.round.x,this.round.y);else{var g=c+d,j=b+f,h=this.round.x,m=this.round.y,k=this.round.corners;0>f&&(b=j,j=b-f);0>d&&(c=g,g=c-d);2*h>d&&(h=0.5*d);2*m>f&&(m=0.5*f);!k||k[0]?a.moveTo(c+h,b):a.moveTo(c,b);!k||k[1]?(a.lineTo(g-h,b),a.quadraticCurveTo(g,b,g,b+m)):a.lineTo(g,
b);!k||k[2]?(a.lineTo(g,j-m),a.quadraticCurveTo(g,j,g-h,j)):a.lineTo(g,j);!k||k[3]?(a.lineTo(c+h,j),a.quadraticCurveTo(c,j,c,j-m)):a.lineTo(c,j);!k||k[0]?(a.lineTo(c,b+m),a.quadraticCurveTo(c,b,c+h,b)):a.lineTo(c,b);a.closePath()}};this.textHeight=function(){return 1.3*this.font.getSize()};this.textWidth=function(a){return this.chart.ctx.measureText(a).width};this.draw=function(a,c,b,d,f,g){var j=this._img,h;0<this.transparency&&(h=a.globalAlpha,a.globalAlpha=(1-this.transparency)*h);this.shadow.prepare(a);
j&&j.visible&&""!=j.url?(a.save(),a.clip(),c?(c=c(),j.tryDraw(c.x,c.y,c.width,c.height)):j.tryDraw(b,d,f,g),a.restore()):this.gradient.visible?(a.fillStyle=c?this.gradient.create(c()):this.gradient.rect(b,d,f,g),a.fill()):""!==this.fill&&(a.fillStyle=this.fill,a.fill());""!=this.stroke.fill&&(this.stroke.prepare(),a.stroke());0<this.transparency&&(a.globalAlpha=h)};this.drawText=function(a,c){function b(a){f.fillText(a,h,m);g&&""!=g.fill&&(g.prepare(),f.strokeText(a,h,m))}var d=this.font._g,f=this.chart.ctx,
g=this.font._s,j=this.font.textAlign,h=a.x,m=a.y;f.fillStyle=d&&d.visible&&a?d.create(a):this.font.fill;if("center"==j)h+=0.5*a.width;else if("right"==j||"end"==j)h+=a.width;d=c.split("\n");j=d.length;if(1<j)for(var k=this.textHeight(d[0]),q=0;q<j;q++)b(d[q]),m+=k;else b(c)};this.rectPath=function(a,c,b,d){var f=this.chart.ctx;f.beginPath();0<this.round.x&&0<this.round.y?this.roundRect(f,a,c,b,d):f.rect(a,c,b,d)};this.rectangle=function(a,c,b,d){1>this.transparency&&("object"===typeof a?this.rectangle(a.x,
a.y,a.width,a.height):(this.rectPath(a,c,b,d),this.draw(this.chart.ctx,null,a,c,b,d)))};var b=new r;this.polygon=function(a){var c=this.chart.ctx,d=a.length,i;c.beginPath();c.moveTo(a[0].x,a[0].y);for(i=1;i<d;i++)c.lineTo(a[i].x,a[i].y);c.closePath();this.draw(c,function(){var c=0,d=0,e=0,h=0,i=a.length,k,q;if(0<i){c=e=a[0].x;d=h=a[0].y;for(q=1;q<i;q++)k=a[q].x,k<c?c=k:k>e&&(e=k),k=a[q].y,k<d?d=k:k>h&&(h=k)}b.x=c;b.y=d;b.width=e-c;b.height=h-d;return b})};this.ellipsePath=function(a,c,b,d,f){a.save();
a.translate(c,b);a.scale(0.5*d,0.5*f);a.beginPath();a.arc(0,0,1,0,2*Math.PI,!1);a.restore()};this.ellipse=function(a,c,b,d){var f=this.chart.ctx;this.ellipsePath(f,a,c,b,d);this.draw(f,null,a-0.5*b,c-0.5*d,b,d)}};Tee.Format.prototype.setChart=function(d){this.chart=d;this.shadow.chart=d;this.gradient.chart=d;this.font.setChart(d);this._img&&(this._img.chart=d);this.stroke.setChart(d)};Tee.Annotation=function(d,b,a,c){Tee.Tool.call(this,d);this.position=new p(a||10,c||10);var e=this.margins=new J;
this.items=[];var i=this.bounds=new r;this.visible=!0;this.transparent=!1;this.text=b||"";var f=this.format=new Tee.Format(d);f.font.textAlign="center";f.font.baseLine="top";f.fill="beige";f.round={x:4,y:4};f.stroke.fill="silver";f.shadow.visible=!0;var g,j,h;this.moveTo=function(a,c){this.position.x=a;this.position.y=c;this.resize()};this.resize=function(){if(this.text){f.font.prepare();this.rows=this.text.split("\n");g=f.textHeight(this.text);var a=this.rows.length;j=g*a+e.top;var c,b=j+e.bottom;
if(1<a)for(c=0;a--;)c=Math.max(c,f.textWidth(this.rows[a]+"W"));else c=f.textWidth(this.text+"W");c+=e.left+e.right;var a=this.position,d=a.y+j,h,s;for(h=0;s=this.items[h++];){var l=s.bounds;s.resize();b+=l.height;c=Math.max(c,l.width);l.x=a.x;l.y=d;d+=l.height}for(h=0;s=this.items[h++];)s.bounds.width=c-e.right;i.set(a.x,a.y,c,b)}};this.add=function(a){a=new Tee.Annotation(this.chart,a);this.items.push(a);a.transparent=!0;return a};this.doDraw=function(){if(""!=this.text){this.transparent||f.rectangle(i);
var a,c=this.format.transparency,b=this.chart?this.chart.ctx:null;0<c&&(a=b.globalAlpha,b.globalAlpha=(1-c)*a);f.font.prepare();i.y+=e.top+0.1*g;i.x+=e.left;var d=i.width;i.width-=e.right;f.drawText(i,this.text);i.x=this.position.x;i.y=this.position.y;i.width=d}for(var d=0,h;h=this.items[d++];)h.doDraw();0<c&&(b.globalAlpha=a)};this.clicked=function(a){return this.visible&&i.contains(a)};this.doMouseMove=function(a){(this.mouseinside=this.clicked(a))?(this.cursor&&(this.chart.newCursor=this.cursor),
this.wasinside||(h=new O(250,i,f))):this.wasinside&&(h.restore(),this.chart.draw());this.wasinside=this.mouseinside};this.mousemove=function(a){this.cursor&&"default"!=this.cursor&&this.doMouseMove(a)};this.forceDraw=function(){this.resize();this.doDraw()}};Tee.Annotation.prototype=new Tee.Tool;Tee.Annotation.prototype.draw=function(){this.visible&&this.forceDraw()};Tee.DragTool=function(d){Tee.Tool.call(this,d);this.series=null;var b=this.target={series:null,index:-1};this.clicked=function(){b.series=
null;b.index=-1};var a=new p(0,0);this.mousedown=function(c){var d=this.chart.series.items,i=d.length;this.chart.calcMouse(c,a);b.series=null;b.index=-1;if(this.series&&this.series.visible)b.index=this.series.clicked(a),-1!=b.index&&(b.series=this.series);else for(c=0;c<i;c++)if(d[c].visible&&(b.index=d[c].clicked(a),-1!=b.index)){b.series=d[c];break}return-1!=b.index};this.mousemove=function(a){if(-1!=b.index){var d=b.series,a=d.mandatoryAxis.fromPos(d.yMandatory?a.y:a.x);this.onchanging&&(a=this.onchanging(this,
a));d.data.values[b.index]=a;if(this.onchanged)this.onchanged(this,a);this.chart.draw()}}};Tee.DragTool.prototype=new Tee.Tool;Tee.CursorTool=function(d){Tee.Tool.call(this,d);this.direction="both";this.size=new p(0,0);this.followMouse=!0;this.dragging=-1;this.format=new Tee.Format(d);this.horizAxis=d?d.axes.bottom:null;this.vertAxis=d?d.axes.left:null;var b,a=new r;this.over=function(c){var d=-1;if(a.contains(c)){var e=3>Math.abs(b.x-c.x),c=3>Math.abs(b.y-c.y),h=this.direction;if("both"==h&&e&&c)d=
0;else if(e&&("both"==h||"vertical"==h))d=1;else if(c&&("both"==h||"horizontal"==h))d=2}return d};this.calcRect=function(){var c=d.chartRect;a.x=this.horizAxis?this.horizAxis.startPos:c.x;a.width=this.horizAxis?this.horizAxis.endPos-a.x:c.width;a.y=this.vertAxis?this.vertAxis.startPos:c.y;a.height=this.vertAxis?this.vertAxis.endPos-a.y:c.height};var c=new p(0,0);this.mousedown=function(a){this.chart.calcMouse(a,c);this.dragging=this.followMouse?-1:this.over(c);return-1<this.dragging};this.clicked=
function(){this.dragging=-1};this.mousemove=function(c){var g=this.dragging,j=this.followMouse;if(j||-1<g)if(b||(b=new p),b.x!=c.x||b.y!=c.y)if(this.calcRect(),a.contains(c)){if(j||0==g||1==g)b.x=c.x;if(j||0==g||2==g)b.y=c.y;"full"==this.render?this.chart.draw():(e&&("copy"==this.render?this.chart.ctx.drawImage(e,0,0):(g=d.bounds,i.clearRect(g.x,g.y,g.width,g.height))),this.dodraw("copy"==this.render?this.chart.ctx:i));if(this.onchange)this.onchange(c);return}c=this.over(c);this.chart.newCursor=b&&
-1<c?0==c?"move":1==c?"e-resize":"n-resize":"default"};this.render="copy";var e,i;this.setRender=function(a){this.render=a;e&&(this.resetCopy(),this.chart.draw())};this.resetCopy=function(){var a=this.chart.canvas;"layer"==this.render?(e.style.position="absolute",a.parentNode.appendChild(e),e.style.left=a.offsetLeft,e.style.top=a.offsetTop,e.style.zIndex=10,e.style.pointerEvents="none"):e.parentNode&&e.parentNode.removeChild(e)};this.draw=function(){"full"==this.render?this.dodraw(this.chart.ctx):
(e||(e=this.chart.canvas.cloneNode(),this.resetCopy(),i=e.getContext("2d")),"copy"==this.render?(i.drawImage(d.canvas,0,0),this.dodraw(this.chart.ctx)):this.dodraw(i))};this.dodraw=function(c){var d=this.direction,e="both"==d,h;this.calcRect();b||(b=new p(a.x+0.5*a.width,a.y+0.5*a.height));c.beginPath();if(e||"vertical"==d)h=0.5*this.size.y,c.moveTo(b.x,0==h?a.y:b.y-h),c.lineTo(b.x,0==h?a.y+a.height:b.y+h);if(e||"horizontal"==d)h=0.5*this.size.x,c.moveTo(0==h?a.x:b.x-h,b.y),c.lineTo(0==h?a.x+a.width:
b.x+h,b.y);this.format.stroke.prepare(this.format.stroke.fill,c);c.stroke()}};Tee.CursorTool.prototype=new Tee.Tool;Tee.ToolTip=function(d){function b(){function a(b){c.moveTo(c.oldX+b*c.deltaX,c.oldY+b*c.deltaY);c.autoRedraw&&c.chart.draw()}var d=((new Date).getTime()-c.init)/c.animated;1>d?(a(d),window.requestAnimFrame(b,c)):a(1)}Tee.Annotation.call(this,d);this.visible=!1;this.currentSeries=null;this.currentIndex=-1;this.timID=null;this.autoHide=!1;this.delay=1E3;this.animated=100;this.autoRedraw=
!0;this.render="dom";this.hide=function(){if(this.visible||"dom"==this.render){if(this.onhide)this.onhide(this);this.visible=!1;this.autoRedraw&&("dom"==this.render?Tee.DOMTip.hide():this.chart.draw());this.currentIndex=-1;this.currentSeries=null}};var a=function(a){a&&a[0].hide()};this.mousemove=function(c){for(var b=this.chart.series,d=b.count(),g=null,j,h=0;h<d;h++){var m=b.items[h];if(m.visible&&(j=m.clicked(c),-1!=j)){g=m;break}}if(-1==j)this.hide(),this.currentIndex=-1,this.currentSeries=null;
else if(j!=this.currentIndex||g!=this.currentSeries)if(this.currentIndex=j,this.currentSeries=g)this.refresh(g,j),this.autoHide&&0<this.delay&&(clearTimeout(this.timID),this.timID=window.setTimeout(a,this.delay,[this]))};var c=null;this.refresh=function(a,d){this.visible="dom"!==this.render;this.text=a.markText(d);this.ongettext&&(this.text=this.ongettext(this,this.text,a,d));if(""!=this.text){this.resize();var f=new p;a.calc(d,f);f.x-=0.5*this.bounds.width;f.y-=1.5*this.bounds.height;0>f.x&&(f.x=
0);0>f.y&&(f.y=0);"dom"!==this.render&&!this.autoHide&&0<this.animated&&!isNaN(this.position.x)&&!isNaN(this.position.y)?(this.oldX=this.position.x,this.oldY=this.position.y,this.deltaX=f.x-this.oldX,this.deltaY=f.y-this.oldY,this.init=(new Date).getTime(),c=this,window.requestAnimFrame(b,this)):(this.moveTo(f.x,f.y),this.autoRedraw&&("dom"==this.render?Tee.DOMTip.show(this.text):this.chart.draw()));if(this.onshow)this.onshow(this,a,d)}}};Tee.ToolTip.prototype=new Tee.Annotation;Tee.RainbowPalette=
function(){return"#FF0000 #FF7F00 #FFFF00 #00FF00 #0000FF #6600FF #8B00FF".split(" ")};Tee.Palette=function(d){this.colors=d};Tee.Palette.prototype.get=function(d){return this.colors[-1==d?0:d%this.colors.length]};I.prototype=new Tee.Annotation;w.adjustRect=function(){if(this.visible){var d=0,b=this.labels,a=this.chart.chartRect;if((this.firstSeries=this.hasAnySeries())&&this.visible)this.checkMinMax(),b.checkStyle(),this.custom||(b.visible&&(b.format.font.prepare(),d=this.horizontal?b.format.textHeight("Wj"):
this.minmaxLabelWidth(),b.alternate&&(d*=2),d+=b.padding),this.ticks.visible&&(d+=this.ticks.length),b=this.title,b.visible&&(b.text&&""!=b.text)&&(b.resize(),d+=b.bounds.height),this.horizontal?this.otherSide?a.setTop(a.y+d):a.height-=d:this.otherSide?a.width-=d:a.setLeft(a.x+d))}};w.prototype.setPos=function(d,b){this.startPos=d+0.01*this.start*b;this.endPos=d+0.01*this.end*b;this.axisSize=this.endPos-this.startPos};w.calcRect=function(){if(this.firstSeries){this.checkMinMax();var d=this.chart.chartRect,
b=this.bounds,a=this.horizontal;a?(b.y=this.otherSide?d.y:d.y+d.height,b.width=d.width,this.setPos(d.x,d.width)):(b.x=this.otherSide?d.x+d.width:d.x,b.height=d.height,this.setPos(d.y,d.height));this.calcAxisScale();if(this.automatic){var b=this.chart.series,b=a?b.horizMargins():b.vertMargins(),c=0<b.x,e=0<b.y;c&&(this.minimum-=this.fromSize(b.x));e&&(this.maximum+=this.fromSize(b.y));(c||e)&&this.calcAxisScale()}this.calcScale();b=0.01*(a?d.height:d.width)*this.position;this.axisPos=a?this.otherSide?
d.y+b:d.getBottom()-b:this.otherSide?d.getRight()-b:d.x+b}};w.draw=function(){this.visible&&this.firstSeries&&(""!=this.format.stroke.fill&&this.drawAxis(),this.roundMin()+1E3*this.increm>this.maximum&&(this.grid.visible&&this.drawGrids(),this.ticks.visible&&this.drawTicks(this.ticks,1,0),this.innerTicks.visible&&this.drawTicks(this.innerTicks,-1,0),this.minorTicks.visible&&this.drawTicks(this.minorTicks,1,Math.max(0,this.minorTicks.count)),this.labels.visible&&this.drawLabels()),this.title.visible&&
(this.title.text&&""!=this.title.text)&&this.drawTitle())};L.prototype=new Tee.Annotation;Tee.Series=function(d,b){this.chart=null;this.data={values:[],labels:[],source:null};this.yMandatory=!0;this.horizAxis="bottom";this.vertAxis="left";var a=this.format=new Tee.Format(this.chart),c=this.hover=new Tee.Format(this.chart),e=c.shadow;a.fill="";a.stroke.fill="";this.visible=!0;c.stroke.size=3;c.fill="";c.stroke.fill="red";e.visible=!0;e.color="red";e.blur=10;e.width=0;e.height=0;this.cursor="default";
this.over=-1;this.marks=new L(this,this.chart);this.palette=new Tee.Palette;this.colorEach="auto";this.useAxes=!0;this.decimals=2;this._paintWalls=this._paintAxes=!0;this.init=function(a,c){"object"===typeof a&&a&&(a instanceof Array?(this.data.values=a,c instanceof Array&&(this.data.labels=c)):a instanceof Tee.Chart?(this.chart=a,c instanceof Array&&(this.data.values=c)):(this.data.source=a,this.refresh()))};this.init(d,b);this.getFill=function(a,c){var b=this.palette,b=b&&b.colors?b.get(a):null;
return null==b?this.isColorEach||!c?this.chart.palette.get(a):c.fill:b};this.isNull=function(a){return null===this.data.values[a]};this.getFillStyle=function(c,b){return a.gradient.visible?a.gradient.create(c,b):b};this.recalcAxes=function(){var a=this.chart.axes;this._horizAxis=this.horizAxis instanceof w?this.horizAxis:"top"==this.horizAxis?a.top:a.bottom;this._vertAxis=this.vertAxis instanceof w?this.vertAxis:"right"==this.vertAxis?a.right:a.left;this.mandatoryAxis=this.yMandatory?this._vertAxis:
this._horizAxis;this.notmandatory=this.yMandatory?this._horizAxis:this._vertAxis};this.title="";this.refresh=function(a){this.data.source?this.data.source instanceof HTMLTextAreaElement?(parseText(this.data,this.data.source.value),this.chart&&this.chart.draw()):this.data.source instanceof HTMLInputElement?Tee.doHttpRequest(this,this.data.source.value,function(a,c){parseText(a.data,c);a.chart.draw()},function(c,b){a&&a(this,c,b)}):a&&a(this):this.data.xml?(parseXML(this,this.data.xml),this.chart.draw()):
this.data.json&&(parseJSON(this,this.data.json),this.chart.draw())};this.valueOrLabel=function(a){var c=this.data.labels[a];if(!c||""==c)c=this.valueText(a);return c};this.toPercent=function(a){var c=this.data.values;return(100*c[a]/U(c)).toFixed(this.decimals)+" %"};this.dataText=function(a,c,b,d){function e(a,c){return d?m?[a,c]:[a,""]:a+(c?" "+c:"")}var m=b?this.labelOrTitle(a):this.data.labels[a];return"value"==c?this.valueText(a):"percent"==c?this.toPercent(a):"percentlabel"==c?e(this.toPercent(a),
m):"valuelabel"==c||"auto"==c?e(this.valueText(a),m):"label"==c?m||"":"index"==c?a.toFixed(0):"labelvalue"==c?e(m,this.valueText(a)):"labelpercent"==c?e(m,this.toPercent(a)):this.valueOrLabel(a)};this.markText=function(a){var c=this.marks,b=this.dataText(a,c.style,!1);return c.ongettext?c.ongettext(this,a,b):b};this.valueText=function(a){return(a=(this.data._old||this.data.values)[a])?a instanceof Date?a.format(this.dateFormat):this.valueFormat?a.toLocaleString():(a|0)==a?a.toFixed(0):a.toFixed(this.decimals):
"0"};this.associatedToAxis=function(a){return a.horizontal?"both"==this.horizAxis||this._horizAxis==a:"both"==this.vertAxis||this._vertAxis==a};this.bounds=function(a){var c=this._horizAxis,b=this._vertAxis;a.x=c.calc(this.minXValue());a.width=c.calc(this.maxXValue())-a.x;a.y=b.calc(this.maxYValue());a.height=b.calc(this.minYValue())-a.y};this.calcStack=function(a,c,b){var b=this.pointOrigin(a,!1)+b,d=this.mandatoryAxis;c.x=this.notmandatory.calc(this.data.x?this.data.x[a]:a);this.isStack100?(a=this.pointOrigin(a,
!0),c.y=0==a?d.endPos:d.calc(100*b/a)):c.y=d.calc(b);this.yMandatory||(a=c.x,c.x=c.y,c.y=a)};this.pointOrigin=function(a,c){var b=0,d,e,m=this.chart.series.items,k;for(d=0;d<m.length&&!(e=m[d],!c&&e==this);d++)k=e.data.values,e.visible&&(e.constructor==this.constructor&&k.length>a)&&(e=k[a],void 0!==e&&(b+=c&&0>e?-e:e));return b};this.doHover=function(a){var c=this.chart;if(a!=this.over){if(c.onhover)c.onhover(this,a);this.over=a;this.hover.enabled&&window.requestAnimFrame(function(){c.draw()})}}};
Tee.Series.prototype.setChart=function(d,b){d.chart=b;d.recalcAxes();d.format.setChart(b);d.marks.setChart(b);d.hover.setChart(b)};Tee.Series.prototype.calc=function(d,b){var a=this.data,c=this.notmandatory.calc(a.x?a.x[d]:d),a=this.mandatoryAxis.calc(a.values[d]);b.x=this.yMandatory?c:a;b.y=this.yMandatory?a:c};Tee.Series.prototype.getRect=function(){return new r};Tee.Series.prototype.clicked=function(){return-1};Tee.Series.prototype.labelOrTitle=function(d){return this.data.labels[d]||this.title};
Tee.Series.prototype.mousedown=function(){return!1};Tee.Series.prototype.mousemove=function(d){if(this.hover.enabled||"default"!=this.cursor){var b=this.clicked(d);this.doHover(b);if("default"!=this.cursor&&-1!=b){this.chart.newCursor||(this.chart.newCursor=this.cursor);return}}b=this.marks;if(b.visible){var a=this.data.values.length,c=new p,e;for(e=0;e<a;e+=b.drawEvery)if(!this.isNull(e)&&(this.markPos(e,c),b.canDraw(c.x,c.y,e)&&b.bounds.contains(d))){this.doHover(e);break}}};Tee.Series.prototype.mouseout=
function(){};Tee.Series.prototype.markPos=function(d,b){this.calc(d,b);return!1};Tee.Series.prototype.drawMarks=function(){var d=this.data.values.length,b=new p,a,c;for(a=0;a<d;a+=this.marks.drawEvery)this.isNull(a)||(c=this.markPos(a,b),this.marks.drawMark(b.x,b.y,a,c))};Tee.Series.prototype.horizMargins=function(){};Tee.Series.prototype.vertMargins=function(){};Tee.Series.prototype.minXValue=function(){return this.data.x&&0<this.data.x.length?Math.min.apply({},this.data.x):0};Tee.Series.prototype.minYValue=
function(){var d=this.data.values;return 0<d.length?Math.min.apply({},d):0};Tee.Series.prototype.maxXValue=function(){if(this.data.x)return 0<this.data.x.length?Math.max.apply({},this.data.x):0;var d=this.data.values.length;return 0==d?0:d-1};Tee.Series.prototype.maxYValue=function(){var d=this.data.values,b=d.length,a,c,e;if(0<b){e=Math.max.apply({},d);if(e!==e)for(a=0;a<b;a++)c=d[a],void 0!==c&&(e!==e?e=c:c>e&&(e=c));return e===e?e:0}return 0};Tee.Series.prototype.calcColorEach=function(){this.isColorEach=
"yes"==this.colorEach};Tee.Series.prototype.stackMaxValue=function(){if("100"==this.stacked)return 100;var d=Tee.Series.prototype.maxYValue;if("no"==this.stacked)return d.call(this);for(var d=d.call(this),b=this.data.values,a=b.length,c;a--;)c=b[a],void 0===c&&(c=0),d=Math.max(d,this.pointOrigin(a,!1)+c);return d};Tee.Series.prototype.count=function(){return this.data.values.length};Tee.Series.prototype.addRandom=function(d,b,a){b||(b=1E3);var c=this.data;c.values.length=d;a&&(c.x=Array(d));if(0<
d){c.values[0]=Math.random()*b;a&&(c.x[0]=Math.random()*b);for(var e=1;e<d;e++)c.values[e]=c.values[e-1]+Math.random()*b-0.5*b,a&&(c.x[e]=Math.random()*b)}return this};Tee.Series.prototype.doSort=function(d,b){if("none"==d)return null;for(var a=this.data.values,c=a.length,e=Array(c),i=0;i<c;i++)e[i]=i;if("labels"==d){var a=this.data.labels,f,g,j=b?-1:1,h=b?1:-1;e.sort(function(c,b){f=a[c].toLowerCase();g=a[b].toLowerCase();return f<g?j:f==g?0:h})}else e.sort(b?function(c,b){return a[c]-a[b]}:function(c,
b){return a[b]-a[c]});return e};M.prototype.each=function(d){for(var b=this.items.length,a=0;a<b;a++)d(this.items[a])};Tee.Chart=function(d,b,a){function c(c){i.chart.addSeries(new (a||Tee.Bar)(i.chart)).data.values=c}var e="undefined"!=typeof navigator?navigator.userAgent.toLowerCase():"";this.isChrome=-1<e.indexOf("chrome");this.isAndroid=-1<e.indexOf("android");this.isMozilla=window.mozRequestAnimationFrame;d&&(this.canvas="undefined"!==typeof HTMLCanvasElement&&d instanceof HTMLCanvasElement?
d:"string"==typeof d?document.getElementById(d):d);this.canvas||(this.canvas=document.createElement("canvas"),this.canvas.width=600,this.canvas.height=400);var i=this.canvas;this.bounds=0==i.clientWidth?new r(0,0,i.width,i.height):new r(0,0,i.clientWidth,i.clientHeight);this.chartRect=new r;this.chartRect.setFrom(this.bounds);this.palette=new Tee.Palette("#4466a3 #f39c35 #f14c14 #4e97a8 #2b406b #1d7b63 #b3080e #f2c05d #5db79e #707070 #f3ea8d #b4b4b4".split(" "));this.aspect={chart:this,view3d:!1,
ortogonal:!0,rotation:0,elevation:315,perspective:50,clip:!0,clipRect:function(a){var c=this.chart.ctx;c.save();c.beginPath();c.rect(a.x,a.y,a.width,a.height);c.clip()}};this.panel=new S(this);this.walls={chart:this,visible:!0,left:new G(this),right:new G(this),bottom:new G(this),back:new G(this),draw:function(){var a,c=this.chart.ctx,b=this.transparency;0<b&&(a=c.globalAlpha,c.globalAlpha=(1-b)*a);!this.back.visible||this.back.draw();this.chart.aspect.view3d&&(this.left.visible&&this.left.draw(),
this.bottom.visible&&this.bottom.draw(),this.right.visible&&this.right.draw());0<b&&(c.globalAlpha=a)}};d=this.walls.back.format;d.fill="rgb(240,240,240)";d.shadow.visible=!0;this.axes=new V(this);this.legend=new T(this);this.series=new M(this);this.title=new I(this,"blue");this.title.text="TeeChart";this.footer=new I(this,"red");this.zoom=new Q(this);this.scroll=new R(this);this.tools=new P(this);this.oldPos=new p;this.calcMouse=function(a,c){if(null==a.pageX){var b=document.documentElement&&null!=
document.documentElement.scrollLeft?document.documentElement:document.body;c.x=a.clientX+b.scrollLeft;c.y=a.clientY+b.scrollTop}else c.x=a.pageX,c.y=a.pageY;b=this.canvas;if(b.getBoudingClientRect)b=b.getBoundingClientRect(),c.x-=b.left,c.y-=b.top;else if(b.offsetParent){do c.x-=b.offsetLeft,c.y-=b.offsetTop;while(b=b.offsetParent)}};var f=new p(0,0);this.domousemove=function(a){var c=this.chart;if(c.ctx){a=a||window.event;a.touches&&(a=a.touches[a.touches.length-1]);c.calcMouse(a,f);if(c.scroll.active){var b=
c.scroll.direction,d="both"==b,e;if(d||"horizontal"==b)e=c.axes.bottom.fromSize(c.oldPos.x-f.x),c.axes.top.scroll(e),c.axes.bottom.scroll(e);if(d||"vertical"==b)e=-c.axes.left.fromSize(c.oldPos.y-f.y),c.axes.left.scroll(e),c.axes.right.scroll(e);c.oldPos.x=f.x;c.oldPos.y=f.y;c.scroll.done=!0;if(c.onscroll)c.onscroll(a);c.scroll.done&&window.requestAnimFrame(function(){c.draw()});return!1}if(c.zoom.active){if(f.x!=c.oldPos.x||f.y!=c.oldPos.y)c.zoom.old||(c.zoom.old=new p),c.zoom.old.x=f.x-c.oldPos.x,
c.zoom.old.y=f.y-c.oldPos.y,window.requestAnimFrame(function(){c.draw()}),c.zoom.done=!0;return!1}c.newCursor=null;c.tools.mousemove(f);c.series.mousemove(f);c.legend.mousemove(f);c.title.mousemove(f);a=this.chart.canvas.style;c.newCursor?a.cursor!=c.newCursor&&(c.oldCursor=a.cursor,a.cursor=c.newCursor):void 0!=c.oldCursor&&a.cursor!=c.oldCursor&&(a.cursor=c.oldCursor);return!0}};var g=new p(0,0);this.domousedown=function(a){var a=a||window.event,c=!1,b=this.chart;b.calcMouse(a.touches?a.touches[0]:
a,g);var d=b.series.anyUsesAxes()&&b.chartRect.contains(g);a.touches?1<a.touches.length?(b.zoom.active=b.zoom.enabled&&d,b.zoom.active&&(b.scroll.active=!1)):(b.scroll.active=b.scroll.enabled&&d,b.scroll.active&&(b.zoom.active=!1)):(b.zoom.active=a.button==b.zoom.mouseButton&&b.zoom.enabled&&d,b.scroll.active=a.button==b.scroll.mouseButton&&b.scroll.enabled&&d);b.zoom.done=!1;b.scroll.done=!1;b.oldPos=g;0==a.button?((c=b.tools.mousedown(a))||(c=b.series.mousedown(a)),b.canvas.oncontextmenu=null):
2==a.button&&(b.canvas.oncontextmenu=function(){return!1});c?b.zoom.active=b.scroll.active=!1:c=b.zoom.active||b.scroll.active;a.preventDefault();c&&a.target.setCapture&&a.target.setCapture();return!c};this.domouseup=function(a){var a=a||window.event,c=this.chart,b;c.zoom.active=!1;c.scroll.active=!1;if(c.zoom.done){if(c.zoom.apply()&&c.onzoom)c.onzoom();c.draw();b=!0}else if(b=c.scroll.done,!b&&(b=c.series.clicked(c.oldPos),!b&&(b=c.tools.clicked(c.oldPos),!b&&(b=c.title.clicked(c.oldPos))&&c.title.onclick)))c.title.onclick(c.title);
c.zoom.old=null;c.zoom.done=!1;c.scroll.done=!1;b?a.preventDefault():c.canvas.oncontextmenu=null;a.target.releaseCapture&&a.target.releaseCapture()};i.onmousedown=i.ontouchstart=this.domousedown;i.onmouseup=i.ontouchstop=this.domouseup;i.onmousemove=i.ontouchmove=this.domousemove;i.onmouseout=function(a){a&&!a.target.setCapture&&(this.chart.scroll.active=!1);this.chart.series.mouseout();this.chart.tools.mouseout()};this.addSeries=function(a){a.setChart(a,this);var c=this.series.items,b=c.indexOf(a);
-1==b&&(b=c.push(a)-1);""==a.title&&(a.title="Series"+(1+b).toString());""==a.format.fill&&(a.format.fill=this.palette.get(b));return a};this.removeSeries=function(a){var c=this.series.items,a=c.indexOf(a);-1!=c&&c.splice(a,1)};i.chart=this;if(b&&0<b.length)if(b[0]instanceof Array)for(d=0;d<b.length;d++)c(b[d]);else c(b);this.getSeries=function(a){return this.series.items[a]};this.draw=function(a){var c=this.series;this.ctx=a||(this.canvas.getContext?this.canvas.getContext("2d"):null);if(!this.ctx)throw"Canvas does not provide Context";
this.chartRect.setFrom(this.bounds);this.panel.draw();this.panel.margins.apply(this.chartRect);this.title.tryDraw(!0);this.footer.tryDraw(!1);c.beforeDraw();this.legend.visible&&(this.legend.calcrect(),this.legend.draw());for(var b=c.items.length,d,e=a=!1;b--;)d=c.items[b],d.visible&&(d._paintAxes&&(a=!0),d._paintWalls&&(e=!0));var c=this.axes,f;c.visible&&this.series.anyUsesAxes()&&(c.each(w.adjustRect),c.each(w.calcRect),this.walls.visible&&e&&(this.walls.back.bounds.setFrom(this.chartRect),this.walls.draw()),
0<c.transparency&&(f=this.ctx.globalAlpha,this.ctx.globalAlpha=(1-c.transparency)*f),a&&c.each(w.draw),0<c.transparency&&(this.ctx.globalAlpha=f));this.series.draw();this.tools.draw();this.zoom.active&&this.zoom.draw();if(this.ondraw)this.ondraw(this)};this.toImage=function(a,c,b){if(a=document.getElementById(a))a.src=""!=c?this.canvas.toDataURL(c,b):this.canvas.toDataURL()}};Tee.CustomBar=function(d,b){Tee.Series.call(this,d,b);this.sideMargins=100;this.useOrigin=!0;this.origin=0;this.marks.visible=
!0;this.marks.location="end";this.hover.enabled=!0;this.offset=0;this.barSize=70;this.barStyle="bar";var a=this.format;a.fill="";a.stroke.fill="black";a.shadow.visible=!0;a.round.x=4;a.round.y=4;a.gradient.visible=!0;this.stacked="no";this.drawBar=function(c){if("bar"==this.barStyle)a.rectPath(c.x,c.y,c.width,c.height);else if("line"==this.barStyle){var b;this.yMandatory?(b=c.x+0.5*c.width,a.rectPath(b,c.y,1,c.height)):(b=c.y+0.5*c.height,a.rectPath(c.x,b,c.width,1))}else a.ellipsePath(this.chart.ctx,
c.x+0.5*c.width,c.y+0.5*c.height,c.width,c.height)};this.countAll=function(a){var c=this.chart.series.items,b=0,d=c.length,e,f;for(e=0;e<d&&!(f=c[e],f==this&&a);e++)f.visible&&f.constructor==this.constructor&&(b+=f.data.values.length);return b};var c=new p,e,i=new r,f={total:0,index:0};this._margin=0;this.calcBarOffset=function(a){var b="sideAll"==this.stacked;this.countall=b?this.countAll(!0):0;b=b?this.countAll():this.data.values.length;1<b&&(a/=b-1);"no"==this.stacked?(a/=f.total,c.x=a*(1==f.total?
-0.5:f.index-0.5*f.total),b=f.total):(c.x=0.5*-a,b=1);c.y=0.01*a*this.barSize;this._margin=0.5*b*c.y+0.0050*this.sideMargins*b*(a-c.y);c.x+=0.01*this.offset*a+0.5*(a-c.y)};this.calcStackPos=function(a,c){var b,d,f;this.isStacked?(this.calcStack(a,c,this.data.values[a]),b=this.pointOrigin(a,!1),f=this.mandatoryAxis,this.isStack100?(d=this.pointOrigin(a,!0),e=0==d?f.endPos:f.calc(100*b/d)):e=f.calc(b)):(this.calc(a,c),"sideAll"==this.stacked&&(d=this.notmandatory.calc(this.countall+a),this.yMandatory?
c.x=d:c.y=d))};this.draw=function(){var b=this.data.values.length;if(0<b){this.initOffsets();var d=new p,f=this.chart.ctx;this.hover.enabled||(a.stroke.prepare(),a.shadow.prepare(f));for(var m=0;m<b;m++)if(!this.isNull(m)){this.calcStackPos(m,d);this.calcBarBounds(d,i,c,e);this.drawBar(i);var k=this.hover.enabled&&this.over==m?this.hover:a;f.fillStyle=this.getFillStyle(i,this.getFill(m,k));this.hover.enabled&&k.shadow.prepare(f);f.fill();""!=k.stroke.fill&&(this.hover.enabled&&k.stroke.prepare(),
f.shadowColor="transparent",f.stroke(),k.shadow.visible&&(f.shadowColor=k.shadow.color))}}};this.calcColorEach=function(){this.chart.series.visibleCount(this,Tee.CustomBar,f);this.isColorEach="yes"==this.colorEach||"auto"==this.colorEach&&1==f.total};this.initOffsets=function(){var a=this.notmandatory,c=this.mandatoryAxis,b=this.yMandatory?this.maxXValue()-this.minXValue():this.maxYValue()-this.minYValue();this.calcBarOffset(0==b?a.axisSize:a.calcSize(b));e=this.useOrigin?c.calc(this.origin):this.yMandatory?
c.inverted?c.startPos:c.endPos:c.inverted?c.endPos:c.startPos;this.isStacked="no"!=this.stacked&&"sideAll"!=this.stacked;this.isStack100="100"==this.stacked};this.clicked=function(a){this.initOffsets();var b=new p,d=this.data.values.length,f;for(f=0;f<d;f++)if(!this.isNull(f)&&(this.calcStackPos(f,b),this.calcBarBounds(b,i,c,e),i.contains(a)))return f;return-1};this.markPos=function(a,b){var d=this.yMandatory,f=c.x+0.5*c.y,k=this.marks;this.calcStackPos(a,b);if("sideAll"==this.stacked){var q=this.notmandatory.calc(this.countall+
a);d?b.x=q:b.y=q}q=this.useOrigin&&this.data.values[a]<this.origin;this.mandatoryAxis.inverted&&(q=!q);"center"==k.location&&(this.calcBarBounds(b,i,c,e),k.canDraw(b.x,b.y,a,q)&&(d?b.y=i.y+0.5*i.height+0.5*k.bounds.height:b.x=i.x+0.5*i.width-0.5*k.bounds.width));d?b.x+=f:b.y+=f;return q};this.drawMarks=function(){var a=this.data.values.length,c=this.marks,b=new p,d;if(0<a)for(var e=0;e<a;e+=c.drawEvery)this.isNull(e)||(d=this.markPos(e,b),c.drawMark(b.x,b.y,e,d))};this.labelOrTitle=function(a){var c=
this.title,b=this.data.labels[a];return 1<f.total?c||b:this.parent.labelOrTitle(a)}};Tee.CustomBar.prototype=new Tee.Series;Tee.CustomBar.prototype.parent=Tee.Series.prototype;Tee.CustomBar.constructor=Tee.CustomBar;Tee.Bar=function(d,b){Tee.CustomBar.call(this,d,b);this.calc=function(a,c){this.isStacked?this.calcStack(a,c,this.data.values[a]):this.parent.calc.call(this,a,c)};this.horizMargins=function(a){this.initOffsets();a.x=this._margin;a.y=this._margin};this.vertMargins=function(a){var c=this.marks,
b=this.format.stroke,d=this.minYValue()<this.origin;c.visible&&"center"!==c.location&&(a.y=c.arrow.length+c.format.textHeight("Wj")+c.margins.top+c.margins.bottom,b=c.format.stroke);""!=b.fill&&(a.y+=2*b.size+1);d&&(a.x=a.y)};this.maxXValue=function(){return"sideAll"==this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxYValue=function(){return this.stackMaxValue()};
this.calcBarBounds=function(a,c,b,d){c.x=a.x+b.x;c.width=b.y;this._vertAxis.inverted?(c.y=d,c.height=a.y-c.y):(c.y=a.y,c.height=d-a.y);0>c.height&&(c.y+=c.height,c.height=-c.height)}};Tee.Bar.prototype=new Tee.CustomBar;Tee.Bar.prototype.parent=Tee.CustomBar.prototype;Tee.HorizBar=function(d,b){Tee.CustomBar.call(this,d,b);this.yMandatory=!1;this.format.gradient.direction="rightleft";this.maxMarkWidth=function(){var a=0,c,b,d=this.marks,f=this.count(),g;if(d.visible){c=this.marks.format;c.font.prepare();
for(b=0;b<f;b+=d.drawEvery)this.isNull(b)||(g=c.textWidth(this.markText(b)+"W"),g>a&&(a=g))}return a};this.horizMargins=function(a){var c=this.marks,b=this.format.stroke,d=this.minXValue()<this.origin;c.visible&&"center"!==c.location&&(a.y=c.arrow.length+this.maxMarkWidth()+c.margins.left+c.margins.right,b=c.format.stroke);""!=b.fill&&(a.y+=2*b.size+1);d&&(a.x=a.y)};this.vertMargins=function(a){this.initOffsets();a.x+=this._margin;a.y+=this._margin};this.maxYValue=function(){return"sideAll"==this.stacked?
this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){return"sideAll"==this.stacked?0:this.parent.minXValue.call(this)};this.minXValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxXValue=function(){return this.stackMaxValue()};this.calcBarBounds=function(a,c,b,d){c.y=a.y+b.x;c.height=b.y;this._horizAxis.inverted?(c.x=a.x,c.width=d-a.x):(c.x=d,c.width=a.x-c.x);0>c.width&&(c.x+=c.width,c.width=-c.width)}};Tee.HorizBar.prototype=
new Tee.CustomBar;Tee.HorizBar.prototype.parent=Tee.CustomBar.prototype;Tee.CustomSeries=function(d,b){Tee.Series.call(this,d,b);this.stacked="no";this.stairs=!1;this.hover.enabled=!0;this.isStack100=this.isStacked=this.hover.line=!1;this.smooth=0;this.pointer=new function(a){this.setChart=function(a){this.chart=a;this.format.setChart(a)};this.chart=a;a=this.format=new Tee.Format(a);a.shadow.visible=!1;a.fill="";a.gradient.colors=["white","white","white"];a.gradient.visible=!0;a.shadow.visible=!0;
this.colorEach=this.visible=!1;this.style="rectangle";this.height=this.width=12;this.draw=function(a,b,d,f){var g;this.transform&&(g=this.chart.ctx,g.save(),this.transform(a.x,a.y,b));var b=0.5*this.width,j=0.5*this.height;"rectangle"==this.style?d.rectangle(a.x-b,a.y-j,this.width,this.height):"ellipse"==this.style?d.ellipse(a.x,a.y,this.width,this.height):"triangle"==this.style?d.polygon([new p(a.x,a.y-j),new p(a.x-b,a.y+j),new p(a.x+b,a.y+j)]):"downtriangle"==this.style?d.polygon([new p(a.x,a.y+
j),new p(a.x-b,a.y-j),new p(a.x+b,a.y-j)]):"diamond"==this.style?d.polygon([new p(a.x,a.y-j),new p(a.x-b,a.y),new p(a.x,a.y+j),new p(a.x+b,a.y)]):(g.beginPath(),"cross"==this.style&&(g.moveTo(a.x-b,a.y),g.lineTo(a.x+b,a.y),g.moveTo(a.x,a.y-j),g.lineTo(a.x,a.y+j)),"x"==this.style&&(g.moveTo(a.x-b,a.y-j),g.lineTo(a.x+b,a.y+j),g.moveTo(a.x-b,a.y+j),g.lineTo(a.x+b,a.y-j)),d.stroke.prepare(f),g.stroke());this.transform&&g.restore()};this.setSize=function(a){this.height=this.width=a}}(this.chart);this.maxYValue=
function(){return this.stackMaxValue()};this.calc=function(a,c){this.isStacked?this.calcStack(a,c,this.data.values[a]):Tee.Series.prototype.calc.call(this,a,c)};this.calcColorEach=function(){this.isColorEach="yes"==this.colorEach||this.pointer.colorEach}};Tee.CustomSeries.prototype=new Tee.Series;Tee.CustomSeries.prototype.drawPointers=function(){var d=this.data.values.length,b,a=this.pointer.format,c="yes"==this.colorEach||this.pointer.colorEach;!c&&""==a.fill&&(a.fill=this.format.fill);var e=new p,
i=a.gradient,f,g=a.fill;b=g;!c&&i.visible&&i.setEndColor(g);for(f=0;f<d;f++)this.isNull(f)||(this.calc(f,e),g=this.getFill(f,a),g!=b&&(i.visible?i.setEndColor(g):a.fill=g,b=g),this.getSize(f),this.pointer.draw(e,f,a,g),this.hover.enabled&&this.over==f&&this.pointer.draw(e,f,this.hover,g));c&&(a.fill=b)};Tee.CustomSeries.prototype.setChart=function(d,b){var a=Tee.Series.prototype.setChart;a(d,b);d.pointer.setChart(b)};Tee.CustomSeries.prototype.clicked=function(d){var b=new p,a=new p,c=this.data.values.length,
e;if(this.drawLine&&0<c&&(this.hover.line||!this.pointer.visible)){this.calc(0,b);for(e=1;e<c;e++){this.calc(e,a);if(N(d,b,a,3))return e;b.x=a.x;b.y=a.y}}if(this.pointer.visible){b=new r;a=this.pointer;for(e=0;e<c;e++)if(!this.isNull(e)&&(this.calc(e,b),this.getSize(e),b.x-=0.5*a.width,b.width=a.width,b.y-=0.5*a.height,b.height=a.height,b.contains(d)))return e}return-1};Tee.CustomSeries.prototype.horizMargins=function(d){var b=this.pointer,a=b.format.stroke;b.visible&&(d.x=d.y=(""!=a.fill?a.size:
0)+1+0.5*b.width)};Tee.CustomSeries.prototype.vertMargins=function(d){var b=this.pointer,a=b.format.stroke;b.visible&&(d.x=d.y=(""!=a.fill?a.size:0)+1+0.5*b.height)};Tee.CustomSeries.prototype.getSize=function(){};Tee.Line=function(d,b){Tee.CustomSeries.call(this,d,b);this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.shadow.blur=10;a.lineCap="round";this.doDrawLine=function(c){var b=new p,d,f=this.data.values.length,g,j=0,h=f;g=this.notmandatory;!this.smooth&&!this.data.x&&(j=Math.max(0,(g.minimum|
0)-1),h=Math.min(f,(g.maximum|0)+2));c.beginPath();if(0<this.smooth&&"undefined"!==typeof Tee.drawSpline){d=Array(2*f);for(g=0;g<f;g++)this.calc(g,b),d[2*g]=b.x,d[2*g+1]=b.y;Tee.drawSpline(c,d,this.smooth,!0)}else for(g=j;g<h;g++)this.isNull(g)||(this.calc(g,b),g==j?c.moveTo(b.x,b.y):(this.stairs&&c.lineTo(d,b.y),c.lineTo(b.x,b.y)),d=b.x);f=a.stroke;this.chart.isChrome&&a.shadow.visible&&(f.size=Math.max(1.1,f.size));b=f.fill;f.prepare(""==b?a.fill:b);a.shadow.prepare(c);c.stroke()};this.draw=function(){0<
this.data.values.length&&(this.isStacked="no"!=this.stacked,this.isStack100="100"==this.stacked,this.drawLine&&this.doDrawLine(this.chart.ctx),this.pointer.visible&&this.drawPointers())}};Tee.Line.prototype=new Tee.CustomSeries;Tee.PointXY=function(d,b){Tee.Line.call(this,d,b);this.hover.enabled=!0;this.pointer.visible=!0;this.drawLine=!1};Tee.PointXY.prototype=new Tee.Line;Tee.Series.prototype.cellRect=function(d,b,a){var c={total:0,index:-1};d.setFrom(this.chart.chartRect);this.chart.series.visibleCount(this,
a,c);if(b&&1<c.total){b=Math.round(Math.sqrt(c.total));a=Math.round(c.total/b);if(d.width>d.height)var e=b,b=a,a=e;d.width/=b;d.x+=1.03*(c.index%b)*d.width;d.height/=a;d.y+=1.03*(c.index/b|0)*d.height;d.width*=0.94;d.height*=0.94}return d};Tee.Pie=function(d,b){function a(a,c){c.x=h.x+Math.cos(a)*j;c.y=h.y+Math.sin(a)*j}Tee.Series.call(this,d,b);this.marks.style="percent";this.rotation=this.donut=0;this.colorEach="yes";this.useAxes=!1;var c=this.format;c.stroke.fill="black";c.shadow.visible=!0;c.gradient.visible=
!0;c.gradient.direction="radial";c.gradient.colors=["white","white","white"];this.hover.enabled=!0;this.sort="values";this.orderAscending=!1;this.explode=null;this.marks.visible=!0;this.concentric=!1;this.getValue=function(a){return this.data.values[a]};this.calcCenter=function(a,c,b,d){if(this.explode&&(a=this.explode[a]))a=0.01*c*a,d.x+=a*Math.cos(b),d.y+=a*Math.sin(b)};this.clicked=function(a){var c=this.chart.ctx,b=this.data.values.length,d,e;q=k=Math.PI*this.rotation/180;for(d=0;d<b;d++)if(e=
m?m[d]:d,!this.isNull(e)&&(this.slice(c,e),c.isPointInPath(a.x,a.y)))return e;return-1};var e,i,f,g,j,h={x:0,y:0},m,k,q,u;this.slice=function(c,b){var d=new p;q+=2*Math.PI*(Math.abs(this.data.values[b])/e);h.x=i;h.y=f;this.calcCenter(b,g,0.5*(k+q),h);0==this.donut?(d.x=h.x,d.y=h.y):a(k,d);c.beginPath();c.moveTo(d.x,d.y);c.arc(h.x,h.y,g,k,q,!1);0!=this.donut&&a(q,d);c.lineTo(d.x,d.y);0!=this.donut&&c.arc(h.x,h.y,j,q,k,!0);c.closePath();b==this.over&&(u=k);k=q};this.fill=function(a){return this.getFillStyle(this.chart.chartRect,
this.getFill(a))};this.slices=function(a){var b=this.chart.ctx,d=this.data.values.length,e,f;q=k=Math.PI*this.rotation/180;for(e=0;e<d;e++)f=m?m[e]:e,this.isNull(f)||(this.slice(b,f),a?c.shadow.prepare(b):b.fillStyle=this.fill(f),b.fill(),a||(f=c.stroke,""!=f.fill&&(f.prepare(),b.stroke())))};var n=new r;this.draw=function(){if(0<this.data.values.length){var a=0,b=this.marks;c.shadow.visible&&(a+=2*c.shadow.height);b.visible&&(b.format.font.prepare(),a+=b.format.textHeight("Wj")+0.5*b.arrow.length);
this.cellRect(n,!this.concentric,Tee.Pie);i=n.x+0.5*n.width;f=n.y+0.5*n.height;g=0.5*n.width;a=0.5*(n.height-2*a);0>a&&(a=0);a<g&&(g=a);j=0.01*g*this.donut;for(var a=this.data.values,b=0,d=a.length;d--;)b+=0<a[d]?a[d]:-a[d];e=b;m=this.doSort(this.sort,this.orderAscending);this.slices(!0);this.slices(!1);this.hover.enabled&&-1!=this.over&&(a=this.hover,""!=a.stroke.fill&&(q=k=u,b=this.chart.ctx,this.slice(b,this.over),b.fillStyle=this.fill(this.over),a.draw(b,null,n.x,n.y,n.width,n.height)))}};this.drawMarks=
function(){var a=k=Math.PI*this.rotation/180,b,c=this.data.values,d=c.length,j,n;for(n=0;n<d;n+=this.marks.drawEvery)j=m?m[n]:n,this.isNull(j)||(a+=2*Math.PI*(c[j]/e),b=0.5*(k+a),h.x=i,h.y=f,this.calcCenter(n,g,b,h),this.marks.drawPolar(h,g,b,j),k=a)}};Tee.Pie.prototype=new Tee.Series;Tee.Area=function(d,b){Tee.CustomSeries.call(this,d,b);this.useOrigin=!1;this.origin=0;this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.lineCap="round";a.stroke.fill="black";a.fill="";var c=new r;this.draw=function(){var b=
this.data.values.length;if(0<b){var d=this.mandatoryAxis,f=this.notmandatory,g,j=this.yMandatory;g=this.useOrigin?d.calc(this.origin):j&&d.inverted||!j&&!d.inverted?d.startPos:d.endPos;this.isStacked="no"!=this.stacked;this.isStack100="100"==this.stacked;var h=new p,m,k,d=this.chart.ctx,q,u=this.isStacked,n=0,s=b;!this.smooth&&!this.data.x&&(n=Math.max(0,(f.minimum|0)-1),s=Math.min(b,(f.maximum|0)+2));d.beginPath();if(0<this.smooth&&"undefined"!==typeof Tee.drawSpline){q=Array(2*b);for(k=0;k<b;k++)this.calc(k,
h),q[2*k]=h.x,q[2*k+1]=h.y;f=j?q[0]:q[1];Tee.drawSpline(d,q,this.smooth,!0);if(u){var l=0;for(k=b-1;0<=k;k--)this.calcStack(k,h,0),q[l++]=h.x,q[l++]=h.y;d.lineTo(q[0],q[1]);Tee.drawSpline(d,q,this.smooth,!1)}}else if(this.calc(n,h),d.moveTo(h.x,h.y),f=j?h.x:h.y,m=j?h.y:h.x,this.stairs)for(k=n+1;k<s;k++)this.calc(k,h),d.lineTo(h.x,m),d.lineTo(h.x,h.y),m=j?h.y:h.x;else for(k=n+1;k<s;k++)this.calc(k,h),d.lineTo(h.x,h.y);if(u){if(0==this.smooth)for(k=s-1;k>=n;k--)this.calcStack(k,h,0),this.stairs?(d.lineTo(h.x,
m),d.lineTo(h.x,h.y),m=j?h.y:h.x):d.lineTo(h.x,h.y)}else j?(d.lineTo(h.x,g),d.lineTo(f,g)):(d.lineTo(g,h.y),d.lineTo(g,f));d.closePath();b=a.gradient;b.visible&&(b.colors[b.colors.length-1]=a.fill);this.bounds(c);a.draw(d,null,c.x,c.y,c.width,c.height);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=this.yMandatory?Tee.Series.prototype.minYValue.call(this):Tee.Series.prototype.minXValue.call(this);return this.yMandatory?this.useOrigin?Math.min(a,this.origin):a:a};this.minXValue=
function(){var a=this.yMandatory?Tee.Series.prototype.minXValue.call(this):Tee.Series.prototype.minYValue.call(this);return this.yMandatory?a:this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){var a=this.yMandatory?this.stackMaxValue():Tee.Series.prototype.maxXValue.call(this);return this.yMandatory?this.useOrigin?Math.max(a,this.origin):a:a};this.maxXValue=function(){var a=this.yMandatory?Tee.Series.prototype.maxXValue.call(this):this.stackMaxValue();return this.yMandatory?a:this.useOrigin?
Math.max(a,this.origin):a};this.vertMargins=function(b){this.yMandatory&&""!==a.stroke.fill&&(b.y+=a.stroke.size+2)};this.horizMargins=function(b){!this.yMandatory&&""!==a.stroke.fill&&(b.y+=a.stroke.size+2)}};Tee.Area.prototype=new Tee.CustomSeries;Tee.HorizArea=function(d,b){Tee.Area.call(this,d,b);this.yMandatory=!1};Tee.HorizArea.prototype=new Tee.Area;Tee.Donut=function(d,b){Tee.Pie.call(this,d,b);this.donut=50};Tee.Donut.prototype=new Tee.Pie;Tee.Gantt=function(d,b){Tee.Series.call(this,d,b);
this.yMandatory=!1;this.dateFormat="mediumDate";this.hover.enabled=!0;this.hover.round.x=this.hover.round.y=8;this.colorEach="yes";this.data.start=this.data.values;this.data.x=[];this.data.end=[];this.height=70;this.margin=new p(6,6);var a=this.format;a.shadow.visible=!0;a.round.x=a.round.y=8;a.stroke.fill="black";a.gradient.visible=!0;var c=new r,e;this.addRandom=function(a){var b=this.data;b.x.length=a;b.start.length=a;b.end.length=a;if(0<a)for(var c,d,e=0;e<a;e++)b.x[e]=e,c=12*Math.random()|0,
d=10*Math.random()|0,b.start[e]=new Date(2012,c,d),5>c&&(c=5+(7*Math.random()|0)),b.end[e]=new Date(2012,c,d+10*Math.random())};this.bounds=function(a,b){if(this.isNull(a))return!1;this.calc(a,b);b.y-=0.5*e;b.width=this.data.end?this.mandatoryAxis.calcSize(this.data.end[a]-this.data.start[a]):0;b.height=e;return!0};this.add=function(a,b,c,d){var e=this.data;e.labels.push(b);e.x.push(a);e.start.push(c);e.end.push(d)};this.clicked=function(a){var b=this.data.values.length,d;for(d=0;d<b;d++)if(this.bounds(d,
c)&&c.contains(a))return d;return-1};this.draw=function(){var b=this.data.values.length,d,g;e=this.notmandatory.calcSize(0.01*this.height);for(d=0;d<b;d++)this.bounds(d,c)&&(g=this.hover.enabled&&this.over==d?this.hover:a,this.chart.ctx.fillStyle=this.getFillStyle(c,this.getFill(d,g)),g.rectangle(c))};this.horizMargins=function(a){a.x=this.margin.x;a.y=this.margin.y};this.minYValue=function(){return this.parent.minXValue.call(this)-0.5};this.maxYValue=function(){return this.parent.maxXValue.call(this)+
0.5};this.minXValue=function(){return Math.min.apply({},this.data.start)};this.maxXValue=function(){return Math.max.apply({},this.data.end)}};Tee.Gantt.prototype=new Tee.Series;Tee.Gantt.prototype.parent=Tee.Series.prototype;Tee.Bubble=function(d,b){Tee.PointXY.call(this,d,b);var a=this.pointer;a.colorEach=!0;a.style="ellipse";a.format.gradient.visible=!0;a.format.gradient.direction="radial";this.addRandom=function(a){var b=this.data;b.values.length=a;b.radius.length=a;if(0<a)for(var d=0;d<a;d++)b.values[d]=
1E3*Math.random(),b.radius[d]=100*Math.random()}};Tee.Bubble.prototype=new Tee.PointXY;Tee.Bubble.prototype.getSize=function(d){d=this.data.radius?this._vertAxis.calcSize(this.data.radius[d]):0;this.pointer.width=d;this.pointer.height=d};Tee.Bubble.prototype.horizMargins=function(d){this.calcWidth=function(b){this.getSize(b);var b=1+0.5*this.pointer.width,a=this.pointer.format.stroke;""!=a.fill&&(b+=a.size);return b};this.pointer.visible&&(d.x=this.calcWidth(0),d.y=this.calcWidth(this.count()-1))};
Tee.Bubble.prototype.vertMargins=function(d){this.calcHeight=function(b){this.getSize(b);var b=1+0.5*this.pointer.height,a=this.pointer.format.stroke;""!=a.fill&&(b+=a.size);return b};this.pointer.visible&&(d.x=this.calcHeight(0),d.y=this.calcHeight(this.count()-1))};Tee.Volume=function(d,b){Tee.Bar.call(this,d,b);this.barStyle="line";this.colorEach=this.marks.visible=!1;var a=this.format;a.shadow.visible=!1;a.gradient.visible=!1;a.stroke.fill=""};Tee.Volume.prototype=new Tee.Bar;Tee.Candle=function(d,
b){Tee.PointXY.call(this,d,b);this.pointer.width=7;this.pointer.format.stroke.visible=!1;this.higher=this.pointer.format;this.higher.fill="green";this.lower=new Tee.Format(this.chart);this.lower.fill="red";this.lower.stroke.visible=!1;this.style="candle";this.setChart=function(a,b){var d=Tee.PointXY.prototype.setChart;d(a,b);this.lower.setChart(b)};this.draw=function(){var a=this.data,b=a.values.length,d,i=new p,f=this.pointer,g=0.5*f.width,j,h,m,k=this.mandatoryAxis,q,u,n=this.chart.ctx,s,l;for(d=
0;d<b;d++)if(!this.isNull(d)&&(this.calc(d,i),l=i.x,j=k.calc(a.open[d]),h=k.calc(a.high[d]),m=k.calc(a.low[d]),i.y>j?(q=j,u=i.y-j,s=this.lower):(q=i.y,u=j-q,s=this.higher),"bar"==this.style?(n.beginPath(),n.moveTo(l,h),n.lineTo(l,m),n.moveTo(l-g,j),n.lineTo(l,j),n.moveTo(l,i.y),n.lineTo(l+g,i.y),s.stroke.prepare(s.fill),n.stroke()):this.hover.enabled&&this.over==d?this.hover.rectangle(l-g,q,f.width,u):s.rectangle(l-g,q,f.width,u),"openclose"!=this.style&&(h<q||m>q+u)))n.beginPath(),n.moveTo(l,q),
n.lineTo(l,h),n.moveTo(l,q+u),n.lineTo(l,m),this.hover.enabled&&this.over==d?this.hover.stroke.prepare(s.fill):s.stroke.prepare(s.fill),n.stroke()};this.minYValue=function(){return 0<this.data.low.length?Math.min.apply({},this.data.low):0};this.maxYValue=function(){return 0<this.data.high.length?Math.max.apply({},this.data.high):0};this.addRandom=function(a){var b=this.data;b.values.length=a;b.close=b.values;b.open?b.open.length=a:b.open=Array(a);b.high?b.high.length=a:b.high=Array(a);b.low?b.low.length=
a:b.low=Array(a);if(0<a)for(var d=25+100*Math.random(),i,f=0;f<a;f++)i=b.open[f]=d,d=b.close[f]=d+25*Math.random()-12.5,b.high[f]=Math.max(i,d)+15*Math.random(),b.low[f]=Math.min(i,d)-15*Math.random()}};Tee.Candle.prototype=new Tee.PointXY;Tee.Candle.prototype.clicked=function(d){var b=this.pointer.width,a=this.mandatoryAxis,c=this.notmandatory,e=this.data,i=e.values.length,f=new r,g,j,h;f.width=b;for(g=0;g<i;g++)if(!this.isNull(g)&&(f.x=c.calc(g)-0.5*b,j=a.calc(e.open[g]),h=a.calc(e.close[g]),f.y=
j>h?h:j,f.height=Math.abs(j-h),f.contains(d)))return g;return-1};Tee.Candle.prototype.vertMargins=function(){};Tee.Polar=function(d,b){var a,c;function e(a,b,c){if(a.visible){var d=a.axisPos;a.axisPos=b;a.startPos=c-h;a.endPos=c+h;a.drawAxis();a.axisPos=d}}function i(b,d){var e=b.width,f=b.height;a=b.x+0.5*e;c=b.y+0.5*f;h=0.5*Math.min(e,f);d.visible&&d.labels.visible&&(e=d.labels.format.textHeight("W"),h-=e)}Tee.CustomSeries.call(this,d,b);this.pointer.visible=!0;this.rotation=0;this.useOrigin=this._paintWalls=
this._paintAxes=!1;this.origin=0;var f={x:0,y:0},g,j=this.format;c=a=0;var h,m=Math.PI/180;j.stroke.fill="black";this.calc=function(b,d){var e=this.data,f=e.values[b],g=this.mandatoryAxis,e=m*(this.rotation+(e.x?e.x[b]:360*b/e.values.length)),f=(g.inverted?g.maximum-f:f-g.minimum)*h/(g.maximum-g.minimum);d.x=a+Math.cos(e)*f;d.y=c+Math.sin(e)*f};this.beforeDraw=function(){i(this.chart.chartRect,this.notmandatory);var b=this.chart.walls.back;b.visible&&b.format.ellipse(a,c,2*h,2*h);if(this.chart.axes.visible){var b=
this.notmandatory,d=b.grid.format.stroke,f=this.mandatoryAxis,g=0,j=this.chart.ctx,l,p=10,r=b.rotation||0;if(b.visible&&b.labels.visible)for(var t={x:0,y:0,width:0,height:0},w=b.labels.format,v=w.textHeight("W"),y=h+0.8*v,p=Math.max(10,90/(h/v|0)),g=0;360>g;)l=m*(g+r),t.x=a+Math.cos(l)*y,t.y=c+Math.sin(l)*y-0.5*v,w.drawText(t,""+g),g+=p;if(b.visible&&b.grid.visible){p=b.increment||10;j.beginPath();for(g=0;360>g;)l=m*(g+r),j.moveTo(a,c),j.lineTo(a+Math.cos(l)*h,c+Math.sin(l)*h),g+=p;d.prepare(d.fill,
j);j.stroke()}if(f.visible&&f.grid.visible){g=f.roundMin();j=f.grid.format;for(l=2*h/(f.maximum-f.minimum);g<f.maximum;)d=(g-f.minimum)*l,j.ellipse(a,c,d,d),g+=f.increm}e(f,a,c);e(b,c,a)}};this.draw=function(){i(this.chart.chartRect,this.notmandatory);var b=this.data.values.length,d;g=[];for(d=0;d<b;d++)this.isNull(d)||(this.calc(d,f),g.push({x:f.x,y:f.y}));b=g.length;if(0<b){if("bar"==this.style){var e=this.chart.ctx;e.beginPath();for(d=0;d<b;d++)e.moveTo(a,c),e.lineTo(g[d].x,g[d].y);this.format.stroke.prepare(this.format.fill,
e);e.stroke()}else j.polygon(g);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=Tee.Series.prototype.minYValue.call(this);return this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){var a=this.stackMaxValue();return this.useOrigin?Math.max(a,this.origin):a}};Tee.Polar.prototype=new Tee.CustomSeries;var E=0,t,y,H,F="undefined"!==typeof document&&document.all?!0:!1;Tee.DOMTip={show:function(d,b){t||(t=document.createElement("div"),t.setAttribute("id","teetip1"),
t.className="teetip",t.setAttribute("style","padding:5px; margin-left:5px; background-color:#666; border-radius:4px 4px; color:#FFF; z-index:1000;"),document.body.appendChild(t),y=t.style,y.opacity=0,F&&(y.filter="alpha(opacity=0)"));document.onmousemove=this.pos;y.display="block";y.position="absolute";t.innerHTML=d;y.width=b?b+"px":"auto";!b&&F&&(y.width=t.offsetWidth);300<t.offsetWidth&&(y.width="300px");H=parseInt(t.offsetHeight)+3;t.timer&&clearInterval(t.timer);t.timer=setInterval(function(){Tee.DOMTip.fade(1)},
10)},pos:function(d){var b=document.documentElement,a=F?event.clientY+b.scrollTop:d.pageY,d=F?event.clientX+b.scrollLeft:d.pageX;0>a-H&&(a=H);0>d&&(d=0);y.top=a-H+"px";y.left=d+3+"px"},fade:function(d){var b=E;if(97!=b&&1==d||0!=b&&-1==d){var a=10;10>97-b&&1==d?a=97-b:10>E&&-1==d&&(a=b);E=b+a*d;y.opacity=0.01*E;F&&(y.filter="alpha(opacity="+E+")")}else clearInterval(t.timer),-1==d&&(y.display="none",document.onmousemove=null)},hide:function(){t&&(clearInterval(t.timer),t.timer=setInterval(function(){Tee.DOMTip.fade(-1)},
10))}}}).call(this);
