<?php

/**
 * @file
 * TeeChart Module for Drupal.
 * Create charts and graphs using HMTL5 Canvas and JavaScript.
 */
function teechart_init() {
  drupal_add_js(drupal_get_path('module', 'teechart') . '/teechart.js');
}

/**
 * Implements hook_help().
 */
function teechart_help($path, $arg) {
  switch ($path) {
    case 'admin/help#teechart':
      return t('<p>Enables adding charts to content, using custom tags that are replaced by a canvas. See <a href="!filters">filters settings</a>.</p>', array('!filters' => url('admin/config/content/formats')));

    case 'filter#short-tip':
      return t('Add charts <a href="!explanation-url">using special tags</a>', array('!explanation-url' => url('filter/tips', array('fragment' => 'image'))));

    case 'filter#long-tip':
      return t('<p>Charts can be added using custom tags. Tags are replaced by charts using html5 canvas. Syntax: <code>[teechart:title]</code>. Parameter: title is the text to show at chart header.</p>');
  }
}

/**
 * Implements hook_filter_info().
 */
function teechart_filter_info() {
  $filters['teechart'] = array(
    'title' => t('Replace [teechart] tags with live charts.'),
    'process callback' => '_teechart_filter_process',
    'tips callback' => '_teechart_filter_tips',
  );
  return $filters;
}

/**
 * Implements hook_filter_tips().
 */
function _teechart_filter_tips($filter, $format, $long = FALSE) {
  if ($long) {
    return '<p><a id="filter-teechart" name="filter-teechart"></a>' .
      t('Add charts to content using custom tags. Tags are replaced by a canvas. <pre>[teechart:title=Hello Drupal]</pre>') .
      '</p>';
  }
  else {
    return t('Add <a href="!teechart_help">[teechart:xx] tags</a> to display charts.',
      array('!teechart_help' => url("filter/tips/$format->format", array('fragment' => 'filter-teechart'))));
  }
}

function _generateChart($num, $text) {
  $w = 400;
  $h = 300;
  $style = "Bar";
  $legend = "true";
  $title = "TeeChart for Drupal";
  $data = "";
  $labels = "";

  //$params = explode(" ", $text);

  preg_match_all('/"(?:\\\\.|[^\\\\"])*"|\S+/', $text, $matches);

  if (count($matches)>0)
    $params=$matches[0];
  else
    $params=array();

  $count = count($params);
  for ($p=0; $p<$count; $p++) {
    $val = explode("=", $params[$p]);
    if (count($val)==2) {
      switch ($val[0]) {
        case "title": $title=str_replace(array('"', "'"), '', $val[1]); break;
        case "style": $style=str_replace(array('"', "'"), '', $val[1]); break;
       case "legend": $legend=str_replace(array('"', "'"), '', $val[1]); break;
        case "width": $w=str_replace(array('"', "'"), '', $val[1]); break;
       case "height": $h=str_replace(array('"', "'"), '', $val[1]); break;
         case "data": $data=str_replace(array('"', "'"), '', $val[1]); break;
       case "labels": $labels=str_replace('"', '', $val[1]); break;
      }
    }
  }

  $chart = "chart" . $num;

  $replace = "<canvas id='" . $chart . "' width=" . $w . " height=" . $h . "></canvas><script type='text/javascript'>";
  $replace .= "var " . $chart . "=new Tee.Chart('" . $chart . "'); ";

  if ($title != "")
    $replace .= $chart . ".title.text='" . $title . "';";

  if ($legend != "true")
    $replace .= $chart . ".legend.visible=" . $legend . ";";

  if ($data != "") $data="[" . $data . "]";
  $replace .= $chart . ".addSeries(new Tee." . $style . "(" . $data . ")); ";

  if ($labels != "")
    $replace .= $chart . ".series.items[0].data.labels=[" . $labels . "]; ";

  $replace .= $chart . ".draw();";
  $replace .= "</script>";

  return $replace;
}

/**
 * Implements of hook_filter().
 *
 */
function _teechart_filter_process($text, $filter) {
  $num = 1;

  do {
    $i = strpos($text, "[teechart");
    if ($i !== FALSE) {

      $i2 = strpos($text, "]", $i+9);
      if ($i2 !== FALSE) {

        $options=substr($text, $i+10, $i2-$i-1-9);

        //$text = substr($text, 0, $i) . "**" . $options . "**" . substr($text, $i2+1);
        $text = substr($text, 0, $i) . _generateChart($num++, $options) . substr($text, $i2+1);
      }
    }
  }
  while ($i !== FALSE);

  return $text;
}

